<?php


echo !defined("GUVENLIK") ? exit : NULL;
echo "\r\n";
oturumkontrol($url);
if (isset($_GET["islem"]) == "duzenle") {
    $durum = "duzenle";
    $Sorgu = $db->prepare("SELECT * FROM diller WHERE id = ?");
    $Sorgu->execute([$_GET["id"]]);
    if ($Sorgu->rowCount()) {
        $Sonuc = $Sorgu->fetch(PDO::FETCH_ASSOC);
    } else {
        header("Location:" . $url . "/404" . $html . "");
        exit;
    }
}
echo "\r\n<div class=\"page-header\">\r\r\n\t<div class=\"page-title mt-0 mb-0\">\r\r\n\t\t<h3>";
echo $admindil["txt14"];
echo "</h3>\r\r\n\t\t<div class=\"crumbs\">\r\r\n\t\t\t<ul id=\"breadcrumbs\" class=\"breadcrumb\">\r\r\n\t\t\t\t<li><a href=\"./\"><i class=\"icon-home menu-icon\"></i></a></li>\r\r\n\t\t\t\t<li><a href=\"";
echo $sayfalink;
echo "\">";
echo $admindil["txt13"];
echo "</a></li>\r\r\n\t\t\t\t<li class=\"active\"><a href=\"";
echo $sayfalink;
echo "\">";
echo $admindil["txt14"];
echo "</a></li>\r\r\n\t\t\t</ul>\r\r\n\t\t</div>\r\r\n\t</div>\r\r\n</div>\r\r\n<div class=\"row\">\r\r\n\t<div class=\"col-12 grid-margin stretch-card\">\t\t\t\t\r\r\n\t\t<div class=\"card\">\t\t\t\t\t\r\r\n\t\t\t<div class=\"card-body\">\r\r\n\t\t\t\t<div class=\"alert alert-info\" role=\"alert\">\r\r\n\t\t\t\t\t<i class=\"mdi mdi-alert-circle\"></i>\r\r\n\t\t\t\t\tYeni dil ekleme/düzenleme ve multilanguage kullanımı nasıl olur detaylı bilgi almak için <a href=\"\" data-toggle=\"modal\" data-target=\"#exampleModal-2\">lütfen tıklayınız.</a>\r\r\n\t\t\t\t</div>\r\r\n\t\t\t\t<!-- Modal starts -->\r\r\n\t\t\t\t<div class=\"modal fade\" id=\"exampleModal-2\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel-2\" aria-hidden=\"true\">\r\r\n\t\t\t\t\t<div class=\"modal-dialog modal-lg\" role=\"document\">\r\r\n\t\t\t\t\t\t<div class=\"modal-content\">\r\r\n\t\t\t\t\t\t\t<div class=\"modal-header\">\r\r\n\t\t\t\t\t\t\t\t<h5 class=\"modal-title\" id=\"exampleModalLabel-2\">Dil Ekleme/Düzenleme (MultiLanguage Kullanımı) Açıklamalar</h5>\r\r\n\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\r\n\t\t\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\r\n\t\t\t\t\t\t\t\t</button>\r\r\n\t\t\t\t\t\t\t</div>\r\r\n\t\t\t\t\t\t\t<div class=\"modal-body\">\r\r\n\t\t\t\t\t\t\t\t<p>Çoğu yazılımlarımızda standart olarak gelen&nbsp;<span style=\"font-weight: bold;\">Sınırsız Çoklu Dil (Multi Language)</span> sisteminin kullanımı ve <span style=\"font-weight: bold;\">Yeni &nbsp;Dil Ekleme</span> için gerekli bilgiler aşağıda sırasıyla verilmiştir.</p>\r\r\n\t\t\t\t\t\t\t\t<p><span style=\"color: rgb(255, 0, 0);\"><span style=\"font-weight: bold;\">1)</span> </span> Şu anda bulunduğunuz sayfada yer alan standart (dil adı, ön eki, gösterim adı vb. ) ibareleri kendinize göre doldurunuz.</p>\r\r\n\t\t\t\t\t\t\t\t<p><span style=\"font-weight: bold;\"><span style=\"color: rgb(255, 0, 0);\">2)</span> </span>Sayfanın hemen alt kısmında bulunan <span style=\"font-weight: bold;\">Sabit Değişkenler</span> alanındaki Türkçe olarak hazır bulunan ibareleri, ekleyeceğiniz yeni dil'e göre tercüme ederek kaydedin.</p>\r\r\n\t\t\t\t\t\t\t\t<p><span style=\"font-weight: bold;\"><span style=\"color: rgb(255, 0, 0);\">3)</span> </span>Yeni dil ekleme işlemi yaptıktan sonra, eklediğiniz dil'e veri girişi ve düzenleme yapmak için&nbsp;<span style=\"line-height: 21.4286px;\"><span style=\"font-weight: bold;\">Admin Paneli &gt;&gt;&gt; Dil Yönetimi &gt;&gt;&gt; Dil Listesi &gt;&gt;&gt; Eklediğiniz Dili Düzenle</span>'ye tıklayınız. \r\r\n\t\t\t\t\t\t\t\t<p><span style=\"line-height: 21.4286px;\"><span style=\"color: rgb(255, 0, 0); font-weight: bold;\">Hatırlatmakta fayda var;<br></span>Sitede bulunan tüm metinsel alanlar, dil yönetiminden düzenlenebilmektedir. Bu nedenle FTP üzerinden dosyalar da değişiklik yapmanıza <span style=\"text-decoration: underline;\">gerek yoktur</span>. Değiştirmek istediğiniz metinleri, ilgili dil'in içindeki sabit değişkenler kısmından bularak <span style=\"text-decoration: underline;\">değiştirebilirsiniz</span>.</span></p>\r\r\n\t\t\t\t\t\t\t\t<p>\r\r\n\t\t\t\t\t\t\t\t</p>\r\r\n\t\t\t\t\t\t\t</div>\r\r\n\t\t\t\t\t\t</div>\r\r\n\t\t\t\t\t</div>\r\r\n\t\t\t\t</div>\r\r\n\t\t\t\t<!-- Modal Ends -->\r\r\n\t\t\t\t<form class=\"forms-sample\" method=\"post\" action=\"../_class/yonetim_islem.php\" enctype=\"multipart/form-data\">\r\r\n\t\t\t\t<input id=\"id\" name=\"id\" type=\"hidden\" value=\"";
echo $Sonuc["id"];
echo "\">\r\r\n\t\t\t\t\t<div class=\"form-group\">\r\r\n\t\t\t\t\t\t<label for=\"sira\">Sıra</label>\r\r\n\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"sira\" id=\"sira\" value=\"";
echo isset($_GET["islem"]) == "duzenle" ? $Sonuc["sira"] : "";
echo "\" />\r\r\n\t\t\t\t\t</div>\t\r\r\n\t\t\t\t\t<div class=\"form-group\">\r\r\n\t\t\t\t\t\t<label for=\"adi\">Dil Adı</label>\r\r\n\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"adi\" id=\"adi\" value=\"";
echo isset($_GET["islem"]) == "duzenle" ? $Sonuc["adi"] : "";
echo "\" />\r\r\n\t\t\t\t\t</div>\r\r\n\t\t\t\t\t<div class=\"form-group\">\r\r\n\t\t\t\t\t\t<label>Ülke </label>\r\r\n\t\t\t\t\t\t<select class=\"icons_select2\" name=\"bayrak\" style=\"width:100%\">\r\r\n\t\t\t\t\t\t\t<option value=\"0\">Lütfen Seçiniz</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-vi\" data-icon=\"flag-icon-vi\" ";
echo $Sonuc["bayrak"] == "flag-icon-vi" ? "selected" : "";
echo ">ABD Virgin Adaları</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-af\" data-icon=\"flag-icon-af\" ";
echo $Sonuc["bayrak"] == "flag-icon-af" ? "selected" : "";
echo ">Afganistan</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ax\" data-icon=\"flag-icon-ax\" ";
echo $Sonuc["bayrak"] == "flag-icon-ax" ? "selected" : "";
echo ">Aland</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-de\" data-icon=\"flag-icon-de\" ";
echo $Sonuc["bayrak"] == "flag-icon-de" ? "selected" : "";
echo ">Almanya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-us\" data-icon=\"flag-icon-us\" ";
echo $Sonuc["bayrak"] == "flag-icon-us" ? "selected" : "";
echo ">Amerika Birleşik Devletleri</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-um\" data-icon=\"flag-icon-um\" ";
echo $Sonuc["bayrak"] == "flag-icon-um" ? "selected" : "";
echo ">Amerika Birleşik Devletleri Küçük Dış Adaları</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-as\" data-icon=\"flag-icon-as\" ";
echo $Sonuc["bayrak"] == "flag-icon-as" ? "selected" : "";
echo ">Amerikan Samoası</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ad\" data-icon=\"flag-icon-ad\" ";
echo $Sonuc["bayrak"] == "flag-icon-ad" ? "selected" : "";
echo ">Andorra</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ao\" data-icon=\"flag-icon-ao\" ";
echo $Sonuc["bayrak"] == "flag-icon-ao" ? "selected" : "";
echo ">Angora</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ai\" data-icon=\"flag-icon-ai\" ";
echo $Sonuc["bayrak"] == "flag-icon-ai" ? "selected" : "";
echo ">Anguilla</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-aq\" data-icon=\"flag-icon-aq\" ";
echo $Sonuc["bayrak"] == "flag-icon-aq" ? "selected" : "";
echo ">Antarktika</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ag\" data-icon=\"flag-icon-ag\" ";
echo $Sonuc["bayrak"] == "flag-icon-ag" ? "selected" : "";
echo ">Antigua ve Barbuda</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ar\" data-icon=\"flag-icon-ar\" ";
echo $Sonuc["bayrak"] == "flag-icon-ar" ? "selected" : "";
echo ">Arjantin</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-al\" data-icon=\"flag-icon-al\" ";
echo $Sonuc["bayrak"] == "flag-icon-al" ? "selected" : "";
echo ">Arnavutluk</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-aw\" data-icon=\"flag-icon-aw\" ";
echo $Sonuc["bayrak"] == "flag-icon-aw" ? "selected" : "";
echo ">Aruba</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-au\" data-icon=\"flag-icon-au\" ";
echo $Sonuc["bayrak"] == "flag-icon-au" ? "selected" : "";
echo ">Avustralya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-at\" data-icon=\"flag-icon-at\" ";
echo $Sonuc["bayrak"] == "flag-icon-at" ? "selected" : "";
echo ">Avusturya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-az\" data-icon=\"flag-icon-az\" ";
echo $Sonuc["bayrak"] == "flag-icon-az" ? "selected" : "";
echo ">Azerbeycan</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-bs\" data-icon=\"flag-icon-bs\" ";
echo $Sonuc["bayrak"] == "flag-icon-bs" ? "selected" : "";
echo ">Bahamalar</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-bh\" data-icon=\"flag-icon-bh\" ";
echo $Sonuc["bayrak"] == "flag-icon-bh" ? "selected" : "";
echo ">Bahreyn</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-bd\" data-icon=\"flag-icon-bd\" ";
echo $Sonuc["bayrak"] == "flag-icon-bd" ? "selected" : "";
echo ">Bangladeş</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-bb\" data-icon=\"flag-icon-bb\" ";
echo $Sonuc["bayrak"] == "flag-icon-bb" ? "selected" : "";
echo ">Barbados</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-eh\" data-icon=\"flag-icon-eh\" ";
echo $Sonuc["bayrak"] == "flag-icon-eh" ? "selected" : "";
echo ">Batı Sahra</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-by\" data-icon=\"flag-icon-by\" ";
echo $Sonuc["bayrak"] == "flag-icon-by" ? "selected" : "";
echo ">Belarus</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-be\" data-icon=\"flag-icon-be\" ";
echo $Sonuc["bayrak"] == "flag-icon-be" ? "selected" : "";
echo ">Belçika</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-bz\" data-icon=\"flag-icon-bz\" ";
echo $Sonuc["bayrak"] == "flag-icon-bz" ? "selected" : "";
echo ">Belize</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-bj\" data-icon=\"flag-icon-bj\" ";
echo $Sonuc["bayrak"] == "flag-icon-bj" ? "selected" : "";
echo ">Benin</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-bm\" data-icon=\"flag-icon-bm\" ";
echo $Sonuc["bayrak"] == "flag-icon-bm" ? "selected" : "";
echo ">Bermuda</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ae\" data-icon=\"flag-icon-ae\" ";
echo $Sonuc["bayrak"] == "flag-icon-ae" ? "selected" : "";
echo ">Birleşik Arap Emirlikleri</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-gb\" data-icon=\"flag-icon-gb\" ";
echo $Sonuc["bayrak"] == "flag-icon-gb" ? "selected" : "";
echo ">Birleşik Krallık</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-bo\" data-icon=\"flag-icon-bo\" ";
echo $Sonuc["bayrak"] == "flag-icon-bo" ? "selected" : "";
echo ">Bolivya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-bq\" data-icon=\"flag-icon-bq\" ";
echo $Sonuc["bayrak"] == "flag-icon-bq" ? "selected" : "";
echo ">Bonaire</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ba\" data-icon=\"flag-icon-ba\" ";
echo $Sonuc["bayrak"] == "flag-icon-ba" ? "selected" : "";
echo ">Bosna Hersek</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-bw\" data-icon=\"flag-icon-bw\" ";
echo $Sonuc["bayrak"] == "flag-icon-bw" ? "selected" : "";
echo ">Botsvana</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-bv\" data-icon=\"flag-icon-bv\" ";
echo $Sonuc["bayrak"] == "flag-icon-bv" ? "selected" : "";
echo ">Bouvet Adası</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-br\" data-icon=\"flag-icon-br\" ";
echo $Sonuc["bayrak"] == "flag-icon-br" ? "selected" : "";
echo ">Brezilya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-bn\" data-icon=\"flag-icon-bn\" ";
echo $Sonuc["bayrak"] == "flag-icon-bn" ? "selected" : "";
echo ">Brunei Darussalam</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-bg\" data-icon=\"flag-icon-bg\" ";
echo $Sonuc["bayrak"] == "flag-icon-bg" ? "selected" : "";
echo ">Bulgaristan</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-bf\" data-icon=\"flag-icon-bf\" ";
echo $Sonuc["bayrak"] == "flag-icon-bf" ? "selected" : "";
echo ">Burkina Faso</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-bi\" data-icon=\"flag-icon-bi\" ";
echo $Sonuc["bayrak"] == "flag-icon-bi" ? "selected" : "";
echo ">Burundi</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-bt\" data-icon=\"flag-icon-bt\" ";
echo $Sonuc["bayrak"] == "flag-icon-bt" ? "selected" : "";
echo ">Butan</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-td\" data-icon=\"flag-icon-td\" ";
echo $Sonuc["bayrak"] == "flag-icon-td" ? "selected" : "";
echo ">Çad</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-cv\" data-icon=\"flag-icon-cv\" ";
echo $Sonuc["bayrak"] == "flag-icon-cv" ? "selected" : "";
echo ">Cape Verde</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ky\" data-icon=\"flag-icon-ky\" ";
echo $Sonuc["bayrak"] == "flag-icon-ky" ? "selected" : "";
echo ">Cayman Adaları</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-gi\" data-icon=\"flag-icon-gi\" ";
echo $Sonuc["bayrak"] == "flag-icon-gi" ? "selected" : "";
echo ">Cebelitarık</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-cz\" data-icon=\"flag-icon-cz\" ";
echo $Sonuc["bayrak"] == "flag-icon-cz" ? "selected" : "";
echo ">Çek Cumhuriyeti</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-dz\" data-icon=\"flag-icon-dz\" ";
echo $Sonuc["bayrak"] == "flag-icon-dz" ? "selected" : "";
echo ">Cezayir</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-dj\" data-icon=\"flag-icon-dj\" ";
echo $Sonuc["bayrak"] == "flag-icon-dj" ? "selected" : "";
echo ">Cibuti</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-cn\" data-icon=\"flag-icon-cn\" ";
echo $Sonuc["bayrak"] == "flag-icon-cn" ? "selected" : "";
echo ">Çin</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-cc\" data-icon=\"flag-icon-cc\" ";
echo $Sonuc["bayrak"] == "flag-icon-cc" ? "selected" : "";
echo ">Cocos (Keeling) Adaları</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ck\" data-icon=\"flag-icon-ck\" ";
echo $Sonuc["bayrak"] == "flag-icon-ck" ? "selected" : "";
echo ">Cook Adaları</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-cw\" data-icon=\"flag-icon-cw\" ";
echo $Sonuc["bayrak"] == "flag-icon-cw" ? "selected" : "";
echo ">Curacao</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-dk\" data-icon=\"flag-icon-dk\" ";
echo $Sonuc["bayrak"] == "flag-icon-dk" ? "selected" : "";
echo ">Danimarka</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ps\" data-icon=\"flag-icon-ps\" ";
echo $Sonuc["bayrak"] == "flag-icon-ps" ? "selected" : "";
echo ">Devletin Filistin</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-do\" data-icon=\"flag-icon-do\" ";
echo $Sonuc["bayrak"] == "flag-icon-do" ? "selected" : "";
echo ">Dominik Cumhuriyeti</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-dm\" data-icon=\"flag-icon-dm\" ";
echo $Sonuc["bayrak"] == "flag-icon-dm" ? "selected" : "";
echo ">Dominika</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ec\" data-icon=\"flag-icon-ec\" ";
echo $Sonuc["bayrak"] == "flag-icon-ec" ? "selected" : "";
echo ">Ekvador</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-gq\" data-icon=\"flag-icon-gq\" ";
echo $Sonuc["bayrak"] == "flag-icon-gq" ? "selected" : "";
echo ">Ekvator Ginesi</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-sv\" data-icon=\"flag-icon-sv\" ";
echo $Sonuc["bayrak"] == "flag-icon-sv" ? "selected" : "";
echo ">El Salvador</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-id\" data-icon=\"flag-icon-id\" ";
echo $Sonuc["bayrak"] == "flag-icon-id" ? "selected" : "";
echo ">Endonezya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-er\" data-icon=\"flag-icon-er\" ";
echo $Sonuc["bayrak"] == "flag-icon-er" ? "selected" : "";
echo ">Eritre</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-am\" data-icon=\"flag-icon-am\" ";
echo $Sonuc["bayrak"] == "flag-icon-am" ? "selected" : "";
echo ">Ermenistan</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ee\" data-icon=\"flag-icon-ee\" ";
echo $Sonuc["bayrak"] == "flag-icon-ee" ? "selected" : "";
echo ">Estonya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-et\" data-icon=\"flag-icon-et\" ";
echo $Sonuc["bayrak"] == "flag-icon-et" ? "selected" : "";
echo ">Etiyopya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-fk\" data-icon=\"flag-icon-fk\" ";
echo $Sonuc["bayrak"] == "flag-icon-fk" ? "selected" : "";
echo ">Falkland Adaları (Malvinas)</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-fo\" data-icon=\"flag-icon-fo\" ";
echo $Sonuc["bayrak"] == "flag-icon-fo" ? "selected" : "";
echo ">Faroe Adaları</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ma\" data-icon=\"flag-icon-ma\" ";
echo $Sonuc["bayrak"] == "flag-icon-ma" ? "selected" : "";
echo ">Fas</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-fj\" data-icon=\"flag-icon-fj\" ";
echo $Sonuc["bayrak"] == "flag-icon-fj" ? "selected" : "";
echo ">Fiji</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ci\" data-icon=\"flag-icon-ci\" ";
echo $Sonuc["bayrak"] == "flag-icon-ci" ? "selected" : "";
echo ">Fildişi Sahili</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ph\" data-icon=\"flag-icon-ph\" ";
echo $Sonuc["bayrak"] == "flag-icon-ph" ? "selected" : "";
echo ">Filipinler</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-fi\" data-icon=\"flag-icon-fi\" ";
echo $Sonuc["bayrak"] == "flag-icon-fi" ? "selected" : "";
echo ">Finlandiya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-fr\" data-icon=\"flag-icon-fr\" ";
echo $Sonuc["bayrak"] == "flag-icon-fr" ? "selected" : "";
echo ">Fransa</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-tf\" data-icon=\"flag-icon-tf\" ";
echo $Sonuc["bayrak"] == "flag-icon-tf" ? "selected" : "";
echo ">Fransız Güney Bölgesi</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-gf\" data-icon=\"flag-icon-gf\" ";
echo $Sonuc["bayrak"] == "flag-icon-gf" ? "selected" : "";
echo ">Fransız Guyanası</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-pf\" data-icon=\"flag-icon-pf\" ";
echo $Sonuc["bayrak"] == "flag-icon-pf" ? "selected" : "";
echo ">Fransız Polinezyası</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ga\" data-icon=\"flag-icon-ga\" ";
echo $Sonuc["bayrak"] == "flag-icon-ga" ? "selected" : "";
echo ">Gabon</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-gm\" data-icon=\"flag-icon-gm\" ";
echo $Sonuc["bayrak"] == "flag-icon-gm" ? "selected" : "";
echo ">Gambiya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-gh\" data-icon=\"flag-icon-gh\" ";
echo $Sonuc["bayrak"] == "flag-icon-gh" ? "selected" : "";
echo ">Gana</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-gn\" data-icon=\"flag-icon-gn\" ";
echo $Sonuc["bayrak"] == "flag-icon-gn" ? "selected" : "";
echo ">Gine</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-gw\" data-icon=\"flag-icon-gw\" ";
echo $Sonuc["bayrak"] == "flag-icon-gw" ? "selected" : "";
echo ">Gine-Bissau</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-gd\" data-icon=\"flag-icon-gd\" ";
echo $Sonuc["bayrak"] == "flag-icon-gd" ? "selected" : "";
echo ">Grenada</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-gl\" data-icon=\"flag-icon-gl\" ";
echo $Sonuc["bayrak"] == "flag-icon-gl" ? "selected" : "";
echo ">Grönland</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-gp\" data-icon=\"flag-icon-gp\" ";
echo $Sonuc["bayrak"] == "flag-icon-gp" ? "selected" : "";
echo ">Guadeloupe</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-gu\" data-icon=\"flag-icon-gu\" ";
echo $Sonuc["bayrak"] == "flag-icon-gu" ? "selected" : "";
echo ">Guam</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-gt\" data-icon=\"flag-icon-gt\" ";
echo $Sonuc["bayrak"] == "flag-icon-gt" ? "selected" : "";
echo ">Guatemala</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-gg\" data-icon=\"flag-icon-gg\" ";
echo $Sonuc["bayrak"] == "flag-icon-gg" ? "selected" : "";
echo ">Guernsey</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-za\" data-icon=\"flag-icon-za\" ";
echo $Sonuc["bayrak"] == "flag-icon-za" ? "selected" : "";
echo ">Güney Afrika</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-gs\" data-icon=\"flag-icon-gs\" ";
echo $Sonuc["bayrak"] == "flag-icon-gs" ? "selected" : "";
echo ">Güney Georgia ve Güney Sandviç Adaları</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ss\" data-icon=\"flag-icon-ss\" ";
echo $Sonuc["bayrak"] == "flag-icon-ss" ? "selected" : "";
echo ">Güney Sudan</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ge\" data-icon=\"flag-icon-ge\" ";
echo $Sonuc["bayrak"] == "flag-icon-ge" ? "selected" : "";
echo ">Gürcistan</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-gy\" data-icon=\"flag-icon-gy\" ";
echo $Sonuc["bayrak"] == "flag-icon-gy" ? "selected" : "";
echo ">Guyana</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ht\" data-icon=\"flag-icon-ht\" ";
echo $Sonuc["bayrak"] == "flag-icon-ht" ? "selected" : "";
echo ">Haiti</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-hm\" data-icon=\"flag-icon-hm\" ";
echo $Sonuc["bayrak"] == "flag-icon-hm" ? "selected" : "";
echo ">Heard Adası ve McDonald Mcdonald Adaları</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-in\" data-icon=\"flag-icon-in\" ";
echo $Sonuc["bayrak"] == "flag-icon-in" ? "selected" : "";
echo ">Hindistan</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-hr\" data-icon=\"flag-icon-hr\" ";
echo $Sonuc["bayrak"] == "flag-icon-hr" ? "selected" : "";
echo ">Hırvatistan</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-nl\" data-icon=\"flag-icon-nl\" ";
echo $Sonuc["bayrak"] == "flag-icon-nl" ? "selected" : "";
echo ">Hollanda</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-hn\" data-icon=\"flag-icon-hn\" ";
echo $Sonuc["bayrak"] == "flag-icon-hn" ? "selected" : "";
echo ">Honduras</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-hk\" data-icon=\"flag-icon-hk\" ";
echo $Sonuc["bayrak"] == "flag-icon-hk" ? "selected" : "";
echo ">Hong Kong</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-io\" data-icon=\"flag-icon-io\" ";
echo $Sonuc["bayrak"] == "flag-icon-io" ? "selected" : "";
echo ">İngiliz Hint Okyanusu Bölgesi</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-vg\" data-icon=\"flag-icon-vg\" ";
echo $Sonuc["bayrak"] == "flag-icon-vg" ? "selected" : "";
echo ">İngiliz Virgin Adaları</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-iq\" data-icon=\"flag-icon-iq\" ";
echo $Sonuc["bayrak"] == "flag-icon-iq" ? "selected" : "";
echo ">Irak</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ir\" data-icon=\"flag-icon-ir\" ";
echo $Sonuc["bayrak"] == "flag-icon-ir" ? "selected" : "";
echo ">İran, İslam Cumhuriyeti</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ie\" data-icon=\"flag-icon-ie\" ";
echo $Sonuc["bayrak"] == "flag-icon-ie" ? "selected" : "";
echo ">İrlanda</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-im\" data-icon=\"flag-icon-im\" ";
echo $Sonuc["bayrak"] == "flag-icon-im" ? "selected" : "";
echo ">Isle of Man</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-es\" data-icon=\"flag-icon-es\" ";
echo $Sonuc["bayrak"] == "flag-icon-es" ? "selected" : "";
echo ">ispanya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-il\" data-icon=\"flag-icon-il\" ";
echo $Sonuc["bayrak"] == "flag-icon-il" ? "selected" : "";
echo ">İsrail</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-se\" data-icon=\"flag-icon-se\" ";
echo $Sonuc["bayrak"] == "flag-icon-se" ? "selected" : "";
echo ">İsveç</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ch\" data-icon=\"flag-icon-ch\" ";
echo $Sonuc["bayrak"] == "flag-icon-ch" ? "selected" : "";
echo ">İsviçre</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-it\" data-icon=\"flag-icon-it\" ";
echo $Sonuc["bayrak"] == "flag-icon-it" ? "selected" : "";
echo ">İtalya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-is\" data-icon=\"flag-icon-is\" ";
echo $Sonuc["bayrak"] == "flag-icon-is" ? "selected" : "";
echo ">İzlanda</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-jm\" data-icon=\"flag-icon-jm\" ";
echo $Sonuc["bayrak"] == "flag-icon-jm" ? "selected" : "";
echo ">Jamaika</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-jp\" data-icon=\"flag-icon-jp\" ";
echo $Sonuc["bayrak"] == "flag-icon-jp" ? "selected" : "";
echo ">Japonya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-je\" data-icon=\"flag-icon-je\" ";
echo $Sonuc["bayrak"] == "flag-icon-je" ? "selected" : "";
echo ">Jersey</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-kh\" data-icon=\"flag-icon-kh\" ";
echo $Sonuc["bayrak"] == "flag-icon-kh" ? "selected" : "";
echo ">Kamboçya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-cm\" data-icon=\"flag-icon-cm\" ";
echo $Sonuc["bayrak"] == "flag-icon-cm" ? "selected" : "";
echo ">Kamerun</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ca\" data-icon=\"flag-icon-ca\" ";
echo $Sonuc["bayrak"] == "flag-icon-ca" ? "selected" : "";
echo ">Kanada</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-me\" data-icon=\"flag-icon-me\" ";
echo $Sonuc["bayrak"] == "flag-icon-me" ? "selected" : "";
echo ">Karadağ</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-qa\" data-icon=\"flag-icon-qa\" ";
echo $Sonuc["bayrak"] == "flag-icon-qa" ? "selected" : "";
echo ">Katar</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-kz\" data-icon=\"flag-icon-kz\" ";
echo $Sonuc["bayrak"] == "flag-icon-kz" ? "selected" : "";
echo ">Kazakistan</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ke\" data-icon=\"flag-icon-ke\" ";
echo $Sonuc["bayrak"] == "flag-icon-ke" ? "selected" : "";
echo ">Kenya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ki\" data-icon=\"flag-icon-ki\" ";
echo $Sonuc["bayrak"] == "flag-icon-ki" ? "selected" : "";
echo ">Kiribati</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-cy\" data-icon=\"flag-icon-cy\" ";
echo $Sonuc["bayrak"] == "flag-icon-cy" ? "selected" : "";
echo ">Kıbrıs</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-kg\" data-icon=\"flag-icon-kg\" ";
echo $Sonuc["bayrak"] == "flag-icon-kg" ? "selected" : "";
echo ">Kırgızistan</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-co\" data-icon=\"flag-icon-co\" ";
echo $Sonuc["bayrak"] == "flag-icon-co" ? "selected" : "";
echo ">Kolombiya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-km\" data-icon=\"flag-icon-km\" ";
echo $Sonuc["bayrak"] == "flag-icon-km" ? "selected" : "";
echo ">Komorlar</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-cg\" data-icon=\"flag-icon-cg\" ";
echo $Sonuc["bayrak"] == "flag-icon-cg" ? "selected" : "";
echo ">Kongo</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-cd\" data-icon=\"flag-icon-cd\" ";
echo $Sonuc["bayrak"] == "flag-icon-cd" ? "selected" : "";
echo ">Kongo Demokratik Cumhuriyeti</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-kr\" data-icon=\"flag-icon-kr\" ";
echo $Sonuc["bayrak"] == "flag-icon-kr" ? "selected" : "";
echo ">Kore Cumhuriyeti</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-kp\" data-icon=\"flag-icon-kp\" ";
echo $Sonuc["bayrak"] == "flag-icon-kp" ? "selected" : "";
echo ">Kore Demokratik Halk Cumhuriyeti</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-xk\" data-icon=\"flag-icon-xk\" ";
echo $Sonuc["bayrak"] == "flag-icon-xk" ? "selected" : "";
echo ">Kosova</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-cr\" data-icon=\"flag-icon-cr\" ";
echo $Sonuc["bayrak"] == "flag-icon-cr" ? "selected" : "";
echo ">Kosta Rika</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-cu\" data-icon=\"flag-icon-cu\" ";
echo $Sonuc["bayrak"] == "flag-icon-cu" ? "selected" : "";
echo ">Küba</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-kw\" data-icon=\"flag-icon-kw\" ";
echo $Sonuc["bayrak"] == "flag-icon-kw" ? "selected" : "";
echo ">Kuveyt</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-mp\" data-icon=\"flag-icon-mp\" ";
echo $Sonuc["bayrak"] == "flag-icon-mp" ? "selected" : "";
echo ">Kuzey Mariana Adaları</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-la\" data-icon=\"flag-icon-la\" ";
echo $Sonuc["bayrak"] == "flag-icon-la" ? "selected" : "";
echo ">Lao Halkı'nın Demokratik Cumhuriyeti</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ls\" data-icon=\"flag-icon-ls\" ";
echo $Sonuc["bayrak"] == "flag-icon-ls" ? "selected" : "";
echo ">Lesotho</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-lv\" data-icon=\"flag-icon-lv\" ";
echo $Sonuc["bayrak"] == "flag-icon-lv" ? "selected" : "";
echo ">Letonya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-lr\" data-icon=\"flag-icon-lr\" ";
echo $Sonuc["bayrak"] == "flag-icon-lr" ? "selected" : "";
echo ">Liberya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ly\" data-icon=\"flag-icon-ly\" ";
echo $Sonuc["bayrak"] == "flag-icon-ly" ? "selected" : "";
echo ">Libya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-li\" data-icon=\"flag-icon-li\" ";
echo $Sonuc["bayrak"] == "flag-icon-li" ? "selected" : "";
echo ">Lihtenştayn</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-lt\" data-icon=\"flag-icon-lt\" ";
echo $Sonuc["bayrak"] == "flag-icon-lt" ? "selected" : "";
echo ">Litvanya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-lb\" data-icon=\"flag-icon-lb\" ";
echo $Sonuc["bayrak"] == "flag-icon-lb" ? "selected" : "";
echo ">Lübnan</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-lu\" data-icon=\"flag-icon-lu\" ";
echo $Sonuc["bayrak"] == "flag-icon-lu" ? "selected" : "";
echo ">Lüksemburg</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-mo\" data-icon=\"flag-icon-mo\" ";
echo $Sonuc["bayrak"] == "flag-icon-mo" ? "selected" : "";
echo ">Macao</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-hu\" data-icon=\"flag-icon-hu\" ";
echo $Sonuc["bayrak"] == "flag-icon-hu" ? "selected" : "";
echo ">Macaristan</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-mg\" data-icon=\"flag-icon-mg\" ";
echo $Sonuc["bayrak"] == "flag-icon-mg" ? "selected" : "";
echo ">Madagaskar</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-mk\" data-icon=\"flag-icon-mk\" ";
echo $Sonuc["bayrak"] == "flag-icon-mk" ? "selected" : "";
echo ">Makedonya, Eski Yugoslav Cumhuriyeti</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-mw\" data-icon=\"flag-icon-mw\" ";
echo $Sonuc["bayrak"] == "flag-icon-mw" ? "selected" : "";
echo ">Malawi</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-mv\" data-icon=\"flag-icon-mv\" ";
echo $Sonuc["bayrak"] == "flag-icon-mv" ? "selected" : "";
echo ">Maldivler</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-my\" data-icon=\"flag-icon-my\" ";
echo $Sonuc["bayrak"] == "flag-icon-my" ? "selected" : "";
echo ">Malezya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ml\" data-icon=\"flag-icon-ml\" ";
echo $Sonuc["bayrak"] == "flag-icon-ml" ? "selected" : "";
echo ">Mali</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-mt\" data-icon=\"flag-icon-mt\" ";
echo $Sonuc["bayrak"] == "flag-icon-mt" ? "selected" : "";
echo ">Malta</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-mh\" data-icon=\"flag-icon-mh\" ";
echo $Sonuc["bayrak"] == "flag-icon-mh" ? "selected" : "";
echo ">Marşal Adaları</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-mq\" data-icon=\"flag-icon-mq\" ";
echo $Sonuc["bayrak"] == "flag-icon-mq" ? "selected" : "";
echo ">Martinik</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-mu\" data-icon=\"flag-icon-mu\" ";
echo $Sonuc["bayrak"] == "flag-icon-mu" ? "selected" : "";
echo ">Mauritius</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-yt\" data-icon=\"flag-icon-yt\" ";
echo $Sonuc["bayrak"] == "flag-icon-yt" ? "selected" : "";
echo ">Mayotte</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-re\" data-icon=\"flag-icon-re\" ";
echo $Sonuc["bayrak"] == "flag-icon-re" ? "selected" : "";
echo ">Mayotte</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-mx\" data-icon=\"flag-icon-mx\" ";
echo $Sonuc["bayrak"] == "flag-icon-mx" ? "selected" : "";
echo ">Meksika</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-fm\" data-icon=\"flag-icon-fm\" ";
echo $Sonuc["bayrak"] == "flag-icon-fm" ? "selected" : "";
echo ">Mikronezya, Federe Devletleri</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-eg\" data-icon=\"flag-icon-eg\" ";
echo $Sonuc["bayrak"] == "flag-icon-eg" ? "selected" : "";
echo ">Mısır</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-mn\" data-icon=\"flag-icon-mn\" ";
echo $Sonuc["bayrak"] == "flag-icon-mn" ? "selected" : "";
echo ">Moğolistan</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-md\" data-icon=\"flag-icon-md\" ";
echo $Sonuc["bayrak"] == "flag-icon-md" ? "selected" : "";
echo ">Moldova, Cumhuriyeti</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-mc\" data-icon=\"flag-icon-mc\" ";
echo $Sonuc["bayrak"] == "flag-icon-mc" ? "selected" : "";
echo ">Monako</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ms\" data-icon=\"flag-icon-ms\" ";
echo $Sonuc["bayrak"] == "flag-icon-ms" ? "selected" : "";
echo ">Montserrat</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-mr\" data-icon=\"flag-icon-mr\" ";
echo $Sonuc["bayrak"] == "flag-icon-mr" ? "selected" : "";
echo ">Moritanya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-mz\" data-icon=\"flag-icon-mz\" ";
echo $Sonuc["bayrak"] == "flag-icon-mz" ? "selected" : "";
echo ">Mozambik</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-mm\" data-icon=\"flag-icon-mm\" ";
echo $Sonuc["bayrak"] == "flag-icon-mm" ? "selected" : "";
echo ">Myanmar</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-na\" data-icon=\"flag-icon-na\" ";
echo $Sonuc["bayrak"] == "flag-icon-na" ? "selected" : "";
echo ">Namibya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-nr\" data-icon=\"flag-icon-nr\" ";
echo $Sonuc["bayrak"] == "flag-icon-nr" ? "selected" : "";
echo ">Nauru</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-np\" data-icon=\"flag-icon-np\" ";
echo $Sonuc["bayrak"] == "flag-icon-np" ? "selected" : "";
echo ">Nepal</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ne\" data-icon=\"flag-icon-ne\" ";
echo $Sonuc["bayrak"] == "flag-icon-ne" ? "selected" : "";
echo ">Nijer</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ng\" data-icon=\"flag-icon-ng\" ";
echo $Sonuc["bayrak"] == "flag-icon-ng" ? "selected" : "";
echo ">Nijerya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ni\" data-icon=\"flag-icon-ni\" ";
echo $Sonuc["bayrak"] == "flag-icon-ni" ? "selected" : "";
echo ">Nikaragua</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-nu\" data-icon=\"flag-icon-nu\" ";
echo $Sonuc["bayrak"] == "flag-icon-nu" ? "selected" : "";
echo ">Niue</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-cx\" data-icon=\"flag-icon-cx\" ";
echo $Sonuc["bayrak"] == "flag-icon-cx" ? "selected" : "";
echo ">Noel Adası</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-nf\" data-icon=\"flag-icon-nf\" ";
echo $Sonuc["bayrak"] == "flag-icon-nf" ? "selected" : "";
echo ">Norfolk Adası</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-no\" data-icon=\"flag-icon-no\" ";
echo $Sonuc["bayrak"] == "flag-icon-no" ? "selected" : "";
echo ">Norveç</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-cf\" data-icon=\"flag-icon-cf\" ";
echo $Sonuc["bayrak"] == "flag-icon-cf" ? "selected" : "";
echo ">Orta Afrika Cumhuriyeti</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-uz\" data-icon=\"flag-icon-uz\" ";
echo $Sonuc["bayrak"] == "flag-icon-uz" ? "selected" : "";
echo ">Özbekistan</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-pk\" data-icon=\"flag-icon-pk\" ";
echo $Sonuc["bayrak"] == "flag-icon-pk" ? "selected" : "";
echo ">Pakistan</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-pw\" data-icon=\"flag-icon-pw\" ";
echo $Sonuc["bayrak"] == "flag-icon-pw" ? "selected" : "";
echo ">Palau</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-pa\" data-icon=\"flag-icon-pa\" ";
echo $Sonuc["bayrak"] == "flag-icon-pa" ? "selected" : "";
echo ">Panama</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-pg\" data-icon=\"flag-icon-pg\" ";
echo $Sonuc["bayrak"] == "flag-icon-pg" ? "selected" : "";
echo ">Papua Yeni Gine</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-py\" data-icon=\"flag-icon-py\" ";
echo $Sonuc["bayrak"] == "flag-icon-py" ? "selected" : "";
echo ">Paraguay</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-pe\" data-icon=\"flag-icon-pe\" ";
echo $Sonuc["bayrak"] == "flag-icon-pe" ? "selected" : "";
echo ">Peru</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-pn\" data-icon=\"flag-icon-pn\" ";
echo $Sonuc["bayrak"] == "flag-icon-pn" ? "selected" : "";
echo ">Pitcairn</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-pl\" data-icon=\"flag-icon-pl\" ";
echo $Sonuc["bayrak"] == "flag-icon-pl" ? "selected" : "";
echo ">Polonya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-pt\" data-icon=\"flag-icon-pt\" ";
echo $Sonuc["bayrak"] == "flag-icon-pt" ? "selected" : "";
echo ">Portekiz</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-pr\" data-icon=\"flag-icon-pr\" ";
echo $Sonuc["bayrak"] == "flag-icon-pr" ? "selected" : "";
echo ">Porto Riko</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ro\" data-icon=\"flag-icon-ro\" ";
echo $Sonuc["bayrak"] == "flag-icon-ro" ? "selected" : "";
echo ">Romanya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-rw\" data-icon=\"flag-icon-rw\" ";
echo $Sonuc["bayrak"] == "flag-icon-rw" ? "selected" : "";
echo ">Ruanda</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ru\" data-icon=\"flag-icon-ru\" ";
echo $Sonuc["bayrak"] == "flag-icon-ru" ? "selected" : "";
echo ">Rusya Federasyonu</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-bl\" data-icon=\"flag-icon-bl\" ";
echo $Sonuc["bayrak"] == "flag-icon-bl" ? "selected" : "";
echo ">Saint Barthelemy</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-sh\" data-icon=\"flag-icon-sh\" ";
echo $Sonuc["bayrak"] == "flag-icon-sh" ? "selected" : "";
echo ">Saint Helena</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-kn\" data-icon=\"flag-icon-kn\" ";
echo $Sonuc["bayrak"] == "flag-icon-kn" ? "selected" : "";
echo ">Saint Kitts ve Nevis</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-lc\" data-icon=\"flag-icon-lc\" ";
echo $Sonuc["bayrak"] == "flag-icon-lc" ? "selected" : "";
echo ">Saint Lucia</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-mf\" data-icon=\"flag-icon-mf\" ";
echo $Sonuc["bayrak"] == "flag-icon-mf" ? "selected" : "";
echo ">Saint Martin (Fransız bölümü)</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-pm\" data-icon=\"flag-icon-pm\" ";
echo $Sonuc["bayrak"] == "flag-icon-pm" ? "selected" : "";
echo ">Saint Pierre ve Miquelon</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-vc\" data-icon=\"flag-icon-vc\" ";
echo $Sonuc["bayrak"] == "flag-icon-vc" ? "selected" : "";
echo ">Saint Vincent ve Grenadinler</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ws\" data-icon=\"flag-icon-ws\" ";
echo $Sonuc["bayrak"] == "flag-icon-ws" ? "selected" : "";
echo ">Samoa</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-sm\" data-icon=\"flag-icon-sm\" ";
echo $Sonuc["bayrak"] == "flag-icon-sm" ? "selected" : "";
echo ">San Marino</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-st\" data-icon=\"flag-icon-st\" ";
echo $Sonuc["bayrak"] == "flag-icon-st" ? "selected" : "";
echo ">Sao Tome ve Principe</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-sn\" data-icon=\"flag-icon-sn\" ";
echo $Sonuc["bayrak"] == "flag-icon-sn" ? "selected" : "";
echo ">Senegal</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-sc\" data-icon=\"flag-icon-sc\" ";
echo $Sonuc["bayrak"] == "flag-icon-sc" ? "selected" : "";
echo ">Seyşeller</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-sl\" data-icon=\"flag-icon-sl\" ";
echo $Sonuc["bayrak"] == "flag-icon-sl" ? "selected" : "";
echo ">Sierra Leone</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-cl\" data-icon=\"flag-icon-cl\" ";
echo $Sonuc["bayrak"] == "flag-icon-cl" ? "selected" : "";
echo ">Şili</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-sg\" data-icon=\"flag-icon-sg\" ";
echo $Sonuc["bayrak"] == "flag-icon-sg" ? "selected" : "";
echo ">Singapur</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-sx\" data-icon=\"flag-icon-sx\" ";
echo $Sonuc["bayrak"] == "flag-icon-sx" ? "selected" : "";
echo ">Sint Maarten (Hollandaca bölümü)</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-rs\" data-icon=\"flag-icon-rs\" ";
echo $Sonuc["bayrak"] == "flag-icon-rs" ? "selected" : "";
echo ">Sırbistan</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-sk\" data-icon=\"flag-icon-sk\" ";
echo $Sonuc["bayrak"] == "flag-icon-sk" ? "selected" : "";
echo ">Slovakya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-si\" data-icon=\"flag-icon-si\" ";
echo $Sonuc["bayrak"] == "flag-icon-si" ? "selected" : "";
echo ">Slovenya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-sb\" data-icon=\"flag-icon-sb\" ";
echo $Sonuc["bayrak"] == "flag-icon-sb" ? "selected" : "";
echo ">Solomon Adaları</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-so\" data-icon=\"flag-icon-so\" ";
echo $Sonuc["bayrak"] == "flag-icon-so" ? "selected" : "";
echo ">Somali</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-lk\" data-icon=\"flag-icon-lk\" ";
echo $Sonuc["bayrak"] == "flag-icon-lk" ? "selected" : "";
echo ">Sri Lanka</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-sd\" data-icon=\"flag-icon-sd\" ";
echo $Sonuc["bayrak"] == "flag-icon-sd" ? "selected" : "";
echo ">Sudan</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-sr\" data-icon=\"flag-icon-sr\" ";
echo $Sonuc["bayrak"] == "flag-icon-sr" ? "selected" : "";
echo ">Surinam</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-sy\" data-icon=\"flag-icon-sy\" ";
echo $Sonuc["bayrak"] == "flag-icon-sy" ? "selected" : "";
echo ">Suriye Arap Cumhuriyeti</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-sa\" data-icon=\"flag-icon-sa\" ";
echo $Sonuc["bayrak"] == "flag-icon-sa" ? "selected" : "";
echo ">Suudi Arabistan</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-sj\" data-icon=\"flag-icon-sj\" ";
echo $Sonuc["bayrak"] == "flag-icon-sj" ? "selected" : "";
echo ">Svalbard ve Jan Mayen</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-sz\" data-icon=\"flag-icon-sz\" ";
echo $Sonuc["bayrak"] == "flag-icon-sz" ? "selected" : "";
echo ">Svaziland</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-tj\" data-icon=\"flag-icon-tj\" ";
echo $Sonuc["bayrak"] == "flag-icon-tj" ? "selected" : "";
echo ">Tacikistan</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-tz\" data-icon=\"flag-icon-tz\" ";
echo $Sonuc["bayrak"] == "flag-icon-tz" ? "selected" : "";
echo ">Tanzanya Birleşik Cumhuriyeti</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-th\" data-icon=\"flag-icon-th\" ";
echo $Sonuc["bayrak"] == "flag-icon-th" ? "selected" : "";
echo ">Tayland</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-tw\" data-icon=\"flag-icon-tw\" ";
echo $Sonuc["bayrak"] == "flag-icon-tw" ? "selected" : "";
echo ">Tayvan</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-tl\" data-icon=\"flag-icon-tl\" ";
echo $Sonuc["bayrak"] == "flag-icon-tl" ? "selected" : "";
echo ">Timor-Leste</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-tg\" data-icon=\"flag-icon-tg\" ";
echo $Sonuc["bayrak"] == "flag-icon-tg" ? "selected" : "";
echo ">Togo</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-tk\" data-icon=\"flag-icon-tk\" ";
echo $Sonuc["bayrak"] == "flag-icon-tk" ? "selected" : "";
echo ">Tokelau</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-to\" data-icon=\"flag-icon-to\" ";
echo $Sonuc["bayrak"] == "flag-icon-to" ? "selected" : "";
echo ">Tonga</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-tt\" data-icon=\"flag-icon-tt\" ";
echo $Sonuc["bayrak"] == "flag-icon-tt" ? "selected" : "";
echo ">Trinidad ve Tobago</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-tn\" data-icon=\"flag-icon-tn\" ";
echo $Sonuc["bayrak"] == "flag-icon-tn" ? "selected" : "";
echo ">Tunus</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-tr\" data-icon=\"flag-icon-tr\" ";
echo $Sonuc["bayrak"] == "flag-icon-tr" ? "selected" : "";
echo ">Türkiye</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-tm\" data-icon=\"flag-icon-tm\" ";
echo $Sonuc["bayrak"] == "flag-icon-tm" ? "selected" : "";
echo ">Türkmenistan</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-tc\" data-icon=\"flag-icon-tc\" ";
echo $Sonuc["bayrak"] == "flag-icon-tc" ? "selected" : "";
echo ">Turks ve Caicos Adaları</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-tv\" data-icon=\"flag-icon-tv\" ";
echo $Sonuc["bayrak"] == "flag-icon-tv" ? "selected" : "";
echo ">Tuvalu</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ug\" data-icon=\"flag-icon-ug\" ";
echo $Sonuc["bayrak"] == "flag-icon-ug" ? "selected" : "";
echo ">Uganda</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ua\" data-icon=\"flag-icon-ua\" ";
echo $Sonuc["bayrak"] == "flag-icon-ua" ? "selected" : "";
echo ">Ukrayna</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-om\" data-icon=\"flag-icon-om\" ";
echo $Sonuc["bayrak"] == "flag-icon-om" ? "selected" : "";
echo ">Umman</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-jo\" data-icon=\"flag-icon-jo\" ";
echo $Sonuc["bayrak"] == "flag-icon-jo" ? "selected" : "";
echo ">Ürdün</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-uy\" data-icon=\"flag-icon-uy\" ";
echo $Sonuc["bayrak"] == "flag-icon-uy" ? "selected" : "";
echo ">Uruguay</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-vu\" data-icon=\"flag-icon-vu\" ";
echo $Sonuc["bayrak"] == "flag-icon-vu" ? "selected" : "";
echo ">Vanuatu</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-va\" data-icon=\"flag-icon-va\" ";
echo $Sonuc["bayrak"] == "flag-icon-va" ? "selected" : "";
echo ">Vatikan</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ve\" data-icon=\"flag-icon-ve\" ";
echo $Sonuc["bayrak"] == "flag-icon-ve" ? "selected" : "";
echo ">Venezuela</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-vn\" data-icon=\"flag-icon-vn\" ";
echo $Sonuc["bayrak"] == "flag-icon-vn" ? "selected" : "";
echo ">Viet Nam</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-wf\" data-icon=\"flag-icon-wf\" ";
echo $Sonuc["bayrak"] == "flag-icon-wf" ? "selected" : "";
echo ">Wallis ve Futuna</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-ye\" data-icon=\"flag-icon-ye\" ";
echo $Sonuc["bayrak"] == "flag-icon-ye" ? "selected" : "";
echo ">Yemen</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-nc\" data-icon=\"flag-icon-nc\" ";
echo $Sonuc["bayrak"] == "flag-icon-nc" ? "selected" : "";
echo ">Yeni Kaledonya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-nz\" data-icon=\"flag-icon-nz\" ";
echo $Sonuc["bayrak"] == "flag-icon-nz" ? "selected" : "";
echo ">Yeni Zelanda</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-gr\" data-icon=\"flag-icon-gr\" ";
echo $Sonuc["bayrak"] == "flag-icon-gr" ? "selected" : "";
echo ">Yunanistan</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-zm\" data-icon=\"flag-icon-zm\" ";
echo $Sonuc["bayrak"] == "flag-icon-zm" ? "selected" : "";
echo ">Zambiya</option>\r\r\n\t\t\t\t\t\t\t<option value=\"flag-icon-zw\" data-icon=\"flag-icon-zw\" ";
echo $Sonuc["bayrak"] == "flag-icon-zw" ? "selected" : "";
echo ">Zimbabve</option>\r\r\n\t\t\t\t\t\t</select>\r\r\n\t\t\t\t\t</div>\r\r\n\t\t\t\t\t<div class=\"form-group float-left mr-3\">\r\r\n\t\t\t\t\t\t<label class=\"d-block\" for=\"durum\">Durum</label>\r\r\n\t\t\t\t\t\t";
if (isset($_GET["islem"]) == "duzenle") {
    echo "\r\n\t\t\t\t\t\t<label class=\"switch\">\r\r\n\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"durum\" id=\"durum\" value=\"1\" ";
    if ($Sonuc["durum"] == "1") {
        echo " checked ";
    }
    echo ">\r\r\n\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\r\n\t\t\t\t\t\t</label>\r\r\n\t\t\t\t\t\t";
} else {
    echo "\r\n\t\t\t\t\t\t<label class=\"switch\">\r\r\n\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"durum\" id=\"durum\" value=\"1\" checked>\r\r\n\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\r\n\t\t\t\t\t\t</label>\r\r\n\t\t\t\t\t\t";
}
echo "\t\t\t\t\t\t\t\t\r\r\n\t\t\t\t\t</div>\r\r\n\t\t\t\t\t\r\r\n\t\t\t\t\t<div class=\"form-group\">\r\r\n\t\t\t\t\t\t<label class=\"d-block\" for=\"anadil\">Anadil</label>\r\r\n\t\t\t\t\t\t";
if (isset($_GET["islem"]) == "duzenle") {
    echo "\r\n\t\t\t\t\t\t<label class=\"switch\">\r\r\n\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"anadil\" id=\"anadil\" value=\"1\" ";
    if ($Sonuc["anadil"] == "1") {
        echo " checked ";
    }
    echo ">\r\r\n\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\r\n\t\t\t\t\t\t</label>\r\r\n\t\t\t\t\t\t";
} else {
    echo "\r\n\t\t\t\t\t\t<label class=\"switch\">\r\r\n\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"anadil\" id=\"anadil\" value=\"1\">\r\r\n\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\r\n\t\t\t\t\t\t</label>\r\r\n\t\t\t\t\t\t";
}
echo "\t\t\t\t\t\t\t\t\r\r\n\t\t\t\t\t</div>\t\t\t\t\t\r\r\n\t\t\t\t\t";
if (isset($_GET["islem"]) == "duzenle") {
    echo "\r\n\t\t\t\t\t<button type=\"submit\" name=\"dil_guncelle\" class=\"btn btn-success btn-icon-text btn-sm\">\r\r\n\t\t\t\t\t\t<i class=\"mdi mdi-reload  btn-icon-prepend\"></i>                                                    \r\r\n\t\t\t\t\t\tGÜNCELLE\r\r\n\t\t\t\t\t</button>\r\r\n\t\t\t\t\t";
} else {
    echo "\r\n\t\t\t\t\t<button type=\"submit\" name=\"dil_ekle\" class=\"btn btn-primary btn-icon-text btn-sm\">\r\r\n\t\t\t\t\t\t<i class=\"mdi mdi-file-check btn-icon-prepend\"></i>\r\r\n\t\t\t\t\t\tKAYDET\r\r\n\t\t\t\t\t</button>\r\r\n\t\t\t\t\t";
}
echo "\r\n\t\t\t\t\t";
if (isset($_GET["islem"]) == "duzenle") {
    echo "\r\n\t\t\t\t\t";
    $dizin = "../language/dil_" . $Sonuc["id"] . ".php";
    $dil = [];
    require_once $dizin;
    $yazan = "";
    if (0 < count($dil)) {
        echo "\r\n\t\t\t\t\t<div class=\"card mt-5\">\r\r\n\t\t\t\t\t\t<div class=\"card-body\">\r\r\n\t\t\t\t\t\t\t<h4 class=\"card-title\">Site Önyüz Dil Ayarı Kelime Düzenle</h4>\r\r\n\t\t\t\t\t\t\t<div class=\"row\">\r\r\n\t\t\t\t\t\t\t\t<div class=\"col-12\">\r\r\n\t\t\t\t\t\t\t\t\t<div class=\"table-responsive\">\r\r\n\t\t\t\t\t\t\t\t\t\t<table id=\"editable-form\" class=\"table table-bordered user-list\">\r\r\n\t\t\t\t\t\t\t\t\t\t\t<thead>\r\r\n\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<th style=\"width:250px;\">Key</th>\r\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Açıklama</th>\r\r\n\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\r\n\t\t\t\t\t\t\t\t\t\t\t</thead>\r\r\n\t\t\t\t\t\t\t\t\t\t\t<tbody>\r\r\n\t\t\t\t\t\t\t\t\t\t\t\t";
        $i = 1;
        foreach ($dil as $key => $d) {
            echo "\r\n\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"uneditable\">";
            echo $key;
            echo "</td>\r\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"text\" id=\"text";
            echo $i++;
            echo "\" value=\"";
            echo $d;
            echo "\" onchange=\"saveData(event,'";
            echo $key;
            echo "')\"><span style=\"display:none\">";
            echo $d;
            echo "</span></td>\t\t\t\t\t\t\t\t\t\t\t\t\t\r\r\n\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\r\n\t\t\t\t\t\t\t\t\t\t\t\t";
        }
        echo "\r\n\t\t\t\t\t\t\t\t\t\t\t</tbody>\r\r\n\t\t\t\t\t\t\t\t\t\t</table>\r\r\n\t\t\t\t\t\t\t\t\t</div>\r\r\n\t\t\t\t\t\t\t\t</div>\r\r\n\t\t\t\t\t\t\t</div>\r\r\n\t\t\t\t\t\t</div>\r\r\n\t\t\t\t\t</div>\r\r\n\t\t\t\t\t";
    } else {
        echo "\r\n\t\t\t\t\t<div class=\"alert alert-danger\">\r\r\n\t\t\t\t\t\t<strong>Kritik Hata!</strong> Dil dosyası bulunamadı veya içi boş acilen ";
        echo str_replace("/", "\\", $dizin);
        echo " yerini doldurun. Veya düzenleye basıp otomatik olarak ekleyebilirsiniz.\r\r\n\t\t\t\t\t</div>\r\r\n\t\t\t\t\t";
    }
    echo "\t\t\t\t\t\t\t\r\r\n\t\t\t\t\t";
}
echo "\r\n\t\t\t\t</form>\r\r\n\t\t\t</div>\r\r\n\t\t</div>\r\r\n\t</div>\r\r\n\r\r\n</div>\r\r\n<style>\r\r\ntable input{\r\r\n\tfont-size:14px;\r\r\n\tpadding:5px 0px;\r\r\n\tdisplay:block;\r\r\n\twidth:100%;\r\r\n\tcolor: #03a9f4;\r\r\n\tcursor:pointer;\r\r\n\tborder:none;\r\r\n\tbackground: transparent;\r\r\n\ttext-decoration: underline;\r\r\n\ttext-decoration-color: #0088cc;\r\r\n\ttext-decoration-style: dashed;\r\r\n\r\r\n}\r\r\ntable input:focus{\r\r\n\toutline: none;\r\r\n\tborder-bottom: 1px dashed #0088cc;\r\r\n\ttext-decoration: none;\r\r\n}\r\r\ntable tr {\r\r\n\tbox-shadow: none;\r\r\n}\r\r\n/* Absolute Center Spinner */\r\r\n.loading {\r\r\n\tposition: fixed;\r\r\n\tz-index: 999;\r\r\n\theight: 2em;\r\r\n\twidth: 2em;\r\r\n\toverflow: visible;\r\r\n\tmargin: auto;\r\r\n\ttop: 0;\r\r\n\tleft: 0;\r\r\n\tbottom: 0;\r\r\n\tright: 0;\r\r\n}\r\r\n\r\r\n/* Transparent Overlay */\r\r\n.loading:before {\r\r\n\tcontent: '';\r\r\n\tdisplay: block;\r\r\n\tposition: fixed;\r\r\n\ttop: 0;\r\r\n\tleft: 0;\r\r\n\twidth: 100%;\r\r\n\theight: 100%;\r\r\n\tbackground-color: rgba(0,0,0,0.3);\r\r\n}\r\r\n\r\r\n/* :not(:required) hides these rules from IE9 and below */\r\r\n.loading:not(:required) {\r\r\n\t/* hide \"loading...\" text */\r\r\n\tfont: 0/0 a;\r\r\n\tcolor: transparent;\r\r\n\ttext-shadow: none;\r\r\n\tbackground-color: transparent;\r\r\n\tborder: 0;\r\r\n}\r\r\n\r\r\n.loading:not(:required):after {\r\r\n\tcontent: '';\r\r\n\tdisplay: block;\r\r\n\tfont-size: 10px;\r\r\n\twidth: 1em;\r\r\n\theight: 1em;\r\r\n\tmargin-top: -0.5em;\r\r\n\t-webkit-animation: spinner 1500ms infinite linear;\r\r\n\t-moz-animation: spinner 1500ms infinite linear;\r\r\n\t-ms-animation: spinner 1500ms infinite linear;\r\r\n\t-o-animation: spinner 1500ms infinite linear;\r\r\n\tanimation: spinner 1500ms infinite linear;\r\r\n\tborder-radius: 0.5em;\r\r\n\t-webkit-box-shadow: rgba(0, 0, 0, 0.75) 1.5em 0 0 0, rgba(0, 0, 0, 0.75) 1.1em 1.1em 0 0, rgba(0, 0, 0, 0.75) 0 1.5em 0 0, rgba(0, 0, 0, 0.75) -1.1em 1.1em 0 0, rgba(0, 0, 0, 0.5) -1.5em 0 0 0, rgba(0, 0, 0, 0.5) -1.1em -1.1em 0 0, rgba(0, 0, 0, 0.75) 0 -1.5em 0 0, rgba(0, 0, 0, 0.75) 1.1em -1.1em 0 0;\r\r\n\tbox-shadow: rgba(0, 0, 0, 0.75) 1.5em 0 0 0, rgba(0, 0, 0, 0.75) 1.1em 1.1em 0 0, rgba(0, 0, 0, 0.75) 0 1.5em 0 0, rgba(0, 0, 0, 0.75) -1.1em 1.1em 0 0, rgba(0, 0, 0, 0.75) -1.5em 0 0 0, rgba(0, 0, 0, 0.75) -1.1em -1.1em 0 0, rgba(0, 0, 0, 0.75) 0 -1.5em 0 0, rgba(0, 0, 0, 0.75) 1.1em -1.1em 0 0;\r\r\n}\r\r\n\r\r\n/* Animation */\r\r\n\r\r\n@-webkit-keyframes spinner {\r\r\n\t0% {\r\r\n\t\t-webkit-transform: rotate(0deg);\r\r\n\t\t-moz-transform: rotate(0deg);\r\r\n\t\t-ms-transform: rotate(0deg);\r\r\n\t\t-o-transform: rotate(0deg);\r\r\n\t\ttransform: rotate(0deg);\r\r\n\t}\r\r\n\t100% {\r\r\n\t\t-webkit-transform: rotate(360deg);\r\r\n\t\t-moz-transform: rotate(360deg);\r\r\n\t\t-ms-transform: rotate(360deg);\r\r\n\t\t-o-transform: rotate(360deg);\r\r\n\t\ttransform: rotate(360deg);\r\r\n\t}\r\r\n}\r\r\n@-moz-keyframes spinner {\r\r\n\t0% {\r\r\n\t\t-webkit-transform: rotate(0deg);\r\r\n\t\t-moz-transform: rotate(0deg);\r\r\n\t\t-ms-transform: rotate(0deg);\r\r\n\t\t-o-transform: rotate(0deg);\r\r\n\t\ttransform: rotate(0deg);\r\r\n\t}\r\r\n\t100% {\r\r\n\t\t-webkit-transform: rotate(360deg);\r\r\n\t\t-moz-transform: rotate(360deg);\r\r\n\t\t-ms-transform: rotate(360deg);\r\r\n\t\t-o-transform: rotate(360deg);\r\r\n\t\ttransform: rotate(360deg);\r\r\n\t}\r\r\n}\r\r\n@-o-keyframes spinner {\r\r\n\t0% {\r\r\n\t\t-webkit-transform: rotate(0deg);\r\r\n\t\t-moz-transform: rotate(0deg);\r\r\n\t\t-ms-transform: rotate(0deg);\r\r\n\t\t-o-transform: rotate(0deg);\r\r\n\t\ttransform: rotate(0deg);\r\r\n\t}\r\r\n\t100% {\r\r\n\t\t-webkit-transform: rotate(360deg);\r\r\n\t\t-moz-transform: rotate(360deg);\r\r\n\t\t-ms-transform: rotate(360deg);\r\r\n\t\t-o-transform: rotate(360deg);\r\r\n\t\ttransform: rotate(360deg);\r\r\n\t}\r\r\n}\r\r\n@keyframes spinner {\r\r\n\t0% {\r\r\n\t\t-webkit-transform: rotate(0deg);\r\r\n\t\t-moz-transform: rotate(0deg);\r\r\n\t\t-ms-transform: rotate(0deg);\r\r\n\t\t-o-transform: rotate(0deg);\r\r\n\t\ttransform: rotate(0deg);\r\r\n\t}\r\r\n\t100% {\r\r\n\t\t-webkit-transform: rotate(360deg);\r\r\n\t\t-moz-transform: rotate(360deg);\r\r\n\t\t-ms-transform: rotate(360deg);\r\r\n\t\t-o-transform: rotate(360deg);\r\r\n\t\ttransform: rotate(360deg);\r\r\n\t}\r\r\n}\r\r\n</style>\r\r\n<div class=\"loader\" style=\"display: none\">\r\r\n    <div class=\"loading\">Lütfen Bekleyiniz</div>\r\r\n</div>\r\r\n<script>\r\r\nfunction iformat(icon) {\r\r\n    var originalOption = icon.element;\r\r\n    return \$('<span><i class=\"flag-icon ' + \$(originalOption).data('icon') + '\"></i> ' + icon.text + '</span>');\r\r\n}\r\r\n\$('.icons_select2').select2({\r\r\n    width: \"100%\",\r\r\n    templateSelection: iformat,\r\r\n    templateResult: iformat,\r\r\n    allowHtml: true\r\r\n});\r\r\n\$(function() {\r\r\n\t\$('#editable-form').DataTable({\r\r\n\t  \"aLengthMenu\": [\r\r\n\t\t[5, 10, 15, -1],\r\r\n\t\t[5, 10, 15, \"Tümü\"]\r\r\n\t  ],\r\r\n\t  \"iDisplayLength\": 10,\r\r\n\t  \"language\": {\r\r\n\t\t\t\"url\":\"js/Turkish.json\"\r\r\n\t\t}\r\r\n\t});\r\r\n\r\r\n\t\$('#order-listing').each(function() {\r\r\n\t\tvar datatable = \$(this);\r\r\n\t\tvar search_input = datatable.closest('.dataTables_wrapper').find('div[id\$=_filter] input');\r\r\n\t\tsearch_input.attr('placeholder', 'Search');\r\r\n\t\tsearch_input.removeClass('form-control-sm');\r\r\n\t\tvar length_sel = datatable.closest('.dataTables_wrapper').find('div[id\$=_length] select');\r\r\n\t\tlength_sel.removeClass('form-control-sm');\r\r\n\t});\r\r\n});\r\r\nfunction saveData(event,key){\r\r\n\tvar value = \$('#'+event.target.id).val();\r\r\n    \$('.loader').show();\r\r\n\r\r\n    \$.post(\"../_class/yonetim_islem.php\",{\r\r\n\t\tkey: key,\r\r\n\t\tvalue: value,\r\r\n\t\tsitedilchange:\"true\",\r\r\n\t\tdil_id:\"";
echo $Sonuc["id"];
echo "\"\r\r\n\t}, function(){\r\r\n        \$('.loader').hide();\r\r\n\r\r\n    ";
if ($_SESSION["rutbe"] == 0) {
    echo "\r\n\t\t\$.toast({\r\r\n\t\t  heading: 'Başarılı!',\r\r\n\t\t  text: 'Başarı ile guncellenmiştir.',\r\r\n\t\t  showHideTransition: 'slide',\r\r\n\t\t  icon: 'success',\r\r\n\t\t  loaderBg: '#fff',\r\r\n\t\t  position: 'top-right'\r\r\n\t\t})\r\r\n\t\t";
} else {
    echo "\r\n\t\t\$.toast({\r\r\n\t\t  heading: 'Uyarı',\r\r\n\t\t  text: 'Demo hesapta işlem yapamassınız.!',\r\r\n\t\t  showHideTransition: 'slide',\r\r\n\t\t  icon: 'warning',\r\r\n\t\t  loaderBg: '#fff',\r\r\n\t\t  position: 'top-right'\r\r\n\t\t})\r\r\n\t\t";
}
echo "\r\n\t});\r\r\n}\r\r\n</script>\r\r\n";
mesaj("dil_ekle", 2, "no", "Hata oluştu tekrar deneyiniz.!");
mesaj("dil_guncelle", 1, "yes", "Başarı ile guncellenmiştir.");
mesaj("dil_guncelle", 2, "no", "Hata oluştu tekrar deneyiniz.!");
echo "\t\t\r\r\n";


?>