<?php


echo !defined("GUVENLIK") ? exit : NULL;
echo "\r\n";
oturumkontrol($url);
echo "\r\n<div class=\"page-header\">\r\r\n\t<div class=\"page-title mt-0 mb-0\">\r\r\n\t\t<h3>Emlak Danışman Mesajları</h3>\r\r\n\t\t<div class=\"crumbs\">\r\r\n\t\t\t<ul id=\"breadcrumbs\" class=\"breadcrumb\">\r\r\n\t\t\t\t<li><a href=\"./\"><i class=\"icon-home menu-icon\"></i></a></li>\r\r\n\t\t\t\t<li class=\"active\"><a href=\"";
echo $sayfalink;
echo "\">Emlak Danışman Mesajları</a></li>\r\r\n\t\t\t</ul>\r\r\n\t\t</div>\r\r\n\t</div>\r\r\n</div>\r\r\n<div class=\"card\">\r\r\n\t<form action=\"../_class/yonetim_islem.php\" method=\"POST\">\r\r\n\t<div class=\"card-body\">\r\r\n\t\t\r\r\n\t\t\r\r\n\t\t<div class=\"row\">\r\r\n\t\t\t<div class=\"col-12\">\r\r\n\t\t\t\t<div class=\"table-responsive\">\r\r\n\t\t\t\t\t<table id=\"order-listingg\" class=\"table table-bordered table-hover\">\r\r\n\t\t\t\t\t\t<thead class=\"headbg\">\r\r\n\t\t\t\t\t\t\t<tr>\r\r\n\t\t\t\t\t\t\t\t<th class=\"noshort\" style=\"width:20px;\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Tümünü Seç\">\r\r\n\t\t\t\t\t\t\t\t\t<input id=\"checkbox-4\" class=\"select-all checkbox-custom\" type=\"checkbox\" style=\"width:100px;\">\r\r\n\t\t\t\t\t\t\t\t\t<label for=\"checkbox-4\" class=\"checkbox-custom-label mb-0\"><span class=\"checktext\"></span></label>\r\r\n\t\t\t\t\t\t\t\t</th>\r\r\n\t\t\t\t\t\t\t\t<th style=\"width:30px;\">ID</th>\r\r\n\t\t\t\t\t\t\t\t<th>Emlak</th>\r\r\n\t\t\t\t\t\t\t\t<th>Danışman</th>\r\r\n\t\t\t\t\t\t\t\t<th>Ad Soyad</th>\r\r\n\t\t\t\t\t\t\t\t<th>Email</th>\r\r\n\t\t\t\t\t\t\t\t<th>Telefon</th>\r\r\n\t\t\t\t\t\t\t\t<th>Mesaj</th>\r\r\n\t\t\t\t\t\t\t\t<th style=\"width:115px;\">İşlem</th>\r\r\n\t\t\t\t\t\t\t</tr>\r\r\n\t\t\t\t\t\t</thead>\r\r\n\t\t\t\t\t\t<tbody id=\"sortable\"></tbody>\r\r\n\t\t\t\t\t</table>\r\r\n\t\t\t\t</div>\r\r\n\t\t\t</div>\r\r\n\t\t</div>\r\r\n\t</div>\r\r\n\t</form>\r\r\n</div>\r\r\n<script>\r\r\n\t\$(document).ready(function(){\r\r\n\t\tvar dataTable=\$('#order-listingg').DataTable({\r\r\n\t\t\t\"processing\": true,\r\r\n\t\t\t\"serverSide\":true,\r\r\n\t\t\t\"ajax\":{\r\r\n\t\t\t\turl:\"data/emlak_mesajlar.php\",\r\r\n\t\t\t\ttype:\"post\"\r\r\n\t\t\t},\r\r\n\t\t\t\"order\": [[ 1, \"asc\" ]],\r\r\n\t\t\t\"aLengthMenu\": [\r\r\n\t\t\t\t[5, 10, 15, 100],\r\r\n\t\t\t\t[5, 10, 15, \"Tümü\"]\r\r\n\t\t\t],\r\r\n\t\t\t\"columnDefs\": [\r\r\n\t\t\t\t{ \"orderable\": false, \"targets\": [0, 4] },\r\r\n\t\t\t\t{ \"targets\": [ 1 ],\"visible\": false },\r\r\n\t\t\t\t{  \"className\": \"secili\", targets: [1, 2] },\r\r\n\t\t\t\t{  \"className\": \"secili text-center\", targets: [3] },\r\r\n\t\t\t\t{  \"className\": \"text-center\", targets: [4] }\r\r\n\t\t\t],\r\r\n\t\t\t\"iDisplayLength\": 10,\r\r\n\t\t\t\"language\": {\r\r\n\t\t\t\t\"url\":\"js/Turkish.json\"\r\r\n\t\t\t},\r\r\n\t\t\t\"fnCreatedRow\": function( nRow, aData, iDataIndex ) {\r\r\n\t\t\t\t\$(nRow).attr('id', 'item-'+aData[1]);\r\r\n\t\t\t},\r\r\n\t\t\t\"fnDrawCallback\": function( oSettings ) {\r\r\n\t\t\t\$(\".popconfirm\").popConfirm();\r\r\n\t\t    }\r\r\n\t\t});\r\r\n\t\t\r\r\n\t});\r\r\n</script>\r\r\n";
mesaj("mesajsil", 1, "yes", "Başarı ile silinmiştir.");
echo "\r\n\t\r\r\n";


?>