<?php


echo !defined("GUVENLIK") ? exit : NULL;
oturumkontrol($url);
if (isset($_GET["islem"]) == "duzenle") {
    $durum = "duzenle";
    $Sorgu = $db->prepare("SELECT * FROM emlaklar WHERE id = ?");
    $Sorgu->execute([$_GET["id"]]);
    if ($Sorgu->rowCount()) {
        $Sonuc = $Sorgu->fetch(PDO::FETCH_ASSOC);
    } else {
        header("Location:" . $url . "/404" . $html . "");
        exit;
    }
}
echo "<div class=\"page-header\">\r\n\t<div class=\"page-title mt-0 mb-0\">\r\n\t\t<h3>";
echo $admindil["txt58"];
echo "</h3>\r\n\t\t<div class=\"crumbs\">\r\n\t\t\t<ul id=\"breadcrumbs\" class=\"breadcrumb\">\r\n\t\t\t\t<li><a href=\"./\"><i class=\"icon-home menu-icon\"></i></a></li>\r\n\t\t\t\t<li><a href=\"";
echo $sayfalink;
echo "\">";
echo $admindil["txt57"];
echo "</a></li>\r\n\t\t\t\t<li><a href=\"emlaklar";
echo $html;
echo "\">";
echo $admindil["txt59"];
echo "</a></li>\r\n\t\t\t\t<li class=\"active\"><a href=\"";
echo $sayfalink;
echo "\">";
echo $admindil["txt58"];
echo "</a></li>\r\n\t\t\t</ul>\r\n\t\t</div>\r\n\t</div>\r\n</div>\r\n<div class=\"row\">\r\n\t<div class=\"col-12 grid-margin stretch-card\">\r\n\t\t<div class=\"card\">\r\n\t\t\t<div class=\"card-body\">\r\n\t\t\t\t<form class=\"forms-sample\" method=\"post\" action=\"../_class/uptade.php\" enctype=\"multipart/form-data\">\r\n\t\t\t\t\t<input id=\"id\" name=\"id\" type=\"hidden\" value=\"";
echo $Sonuc["id"];
echo "\">\r\n\t\t\t\t\t<input id=\"ozellik\" name=\"ozellik\" type=\"hidden\" value=\"";
echo $Sonuc["ozellik"];
echo "\">\r\n\t\t\t\t\t<input id=\"dil\" name=\"dil\" type=\"hidden\" value=\"";
echo $_SESSION["admin_dil"];
echo "\">\r\n\t\t\t\t\t<input id=\"ilceid\" name=\"ilceid\" type=\"hidden\" value=\"";
echo $Sonuc["ilce"];
echo "\">\r\n\t\t\t\t\t<input id=\"semtid\" name=\"semtid\" type=\"hidden\" value=\"";
echo $Sonuc["semt"];
echo "\">\r\n\t\t\t\t\t<input id=\"uye\" name=\"uye\" type=\"hidden\" value=\"";
echo $Sonuc["uye"];
echo "\">\r\n\r\n\t\t\t\t\t<div class=\"row\">\r\n\t\t\t\t\t\t<div class=\"col-3\">\r\n\t\t\t\t\t\t\t<ul class=\"nav nav-tabs nav-tabs-vertical\" role=\"tablist\">\r\n\t\t\t\t\t\t\t\t<li class=\"nav-item\">\r\n\t\t\t\t\t\t\t\t\t<a class=\"nav-link active\" id=\"home-tab-vertical\" data-toggle=\"tab\" href=\"#emlak-bilgileri\" role=\"tab\" aria-controls=\"emlak-bilgileri\" aria-selected=\"true\">\r\n\t\t\t\t\t\t\t\t\t\tEMLAK BİLGİLERİ\r\n\t\t\t\t\t\t\t\t\t</a>\r\n\t\t\t\t\t\t\t\t</li>\r\n\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<li class=\"nav-item\">\r\n\t\t\t\t\t\t\t\t\t<a class=\"nav-link\" id=\"contact-tab-vertical\" data-toggle=\"tab\" href=\"#emlak-ozellikleri\" role=\"tab\" aria-controls=\"emlak-ozellikleri\" aria-selected=\"false\">\r\n\t\t\t\t\t\t\t\t\t\tÖZELLİKLER\r\n\t\t\t\t\t\t\t\t\t</a>\r\n\t\t\t\t\t\t\t\t</li>\r\n\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<li class=\"nav-item\">\r\n\t\t\t\t\t\t\t\t\t<a class=\"nav-link\" id=\"contact-tab-vertical\" data-toggle=\"tab\" href=\"#seo-ayarlari\" role=\"tab\" aria-controls=\"seo-ayarlari\" aria-selected=\"false\">\r\n\t\t\t\t\t\t\t\t\t\tSEO AYARLARI\r\n\t\t\t\t\t\t\t\t\t</a>\r\n\t\t\t\t\t\t\t\t</li>\r\n\t\t\t\t\t\t\t</ul>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div class=\"col-9\">\r\n\t\t\t\t\t\t\t<div class=\"tab-content tab-content-vertical pt-3 pb-0\">\r\n\t\t\t\t\t\t\t\t<div class=\"tab-pane fade show active\" id=\"emlak-bilgileri\" role=\"tabpanel\" aria-labelledby=\"home-tab-vertical\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"adi\">Başlık</label>\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"adi\" id=\"adi\" value=\"";
echo isset($_GET["islem"]) == "duzenle" ? $Sonuc["adi"] : "";
echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n\t\t\t\t\t\t\t\t\t\t<label>İlan Numarası</label>\r\n\t\t\t\t\t\t\t\t\t\t";
$emlakidbul = $db->query("SELECT * FROM emlaklar ORDER BY id desc LIMIT 1")->fetch();
$idtopla = $emlakidbul["id"] + 1;
echo "\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"emlak_kodu\" id=\"emlak_kodu\" value=\"";
echo isset($_GET["islem"]) == "duzenle" ? $Sonuc["emlak_kodu"] : $idtopla;
echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n\t\t\t\t\t\t\t\t\t\t<label>İlan Tarihi <i class=\"icon-info text-info\" data-toggle=\"popover\" data-content=\"İçeriğin ilk eklendiği tarihtir. Sistem ekleme sırasında otomatik olarak verir. Dilerseniz tarihi değiştirebilirsiniz.\" data-trigger=\"hover\" data-original-title=\"İlan Tarihi\"></i></label>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" autocomplete=\"off\" name=\"tarih\" value=\"";
echo isset($_GET["islem"]) == "duzenle" ? $Sonuc["tarih"] : date("d-m-Y H:i");
echo "\" class=\"form-control form-control-sm date-timepicker\" />\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon input-group-append border-left\" style=\"height: 35px;\">\r\n\t\t\t\t\t\t\t\t\t\t\t  <span class=\"mdi mdi-calendar input-group-text\"></span>\r\n\t\t\t\t\t\t\t\t\t\t\t</span>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n\t\t\t\t\t\t\t\t\t<!-- /.form-group -->\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-6\">\r\n\t\t\t\t\t\t\t\t\t\t";
$kategoriler = explode(",", $Sonuc["kategori"]);
echo "\t\t\t\t\t\t\t\t\t\t<label for=\"secenek\">Kategori</label>\r\n\t\t\t\t\t\t\t\t\t\t<select class=\"js-example-basic-multiple form-control-sm\" name=\"kategori\" id=\"secenek\" required style=\"width:100%\">\r\n\t\t\t\t\t\t\t\t\t\t";
emlakkategori(0, 0, $kategoriler);
echo "\t\r\n\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-6\">\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"secenek\">Emlak Danışmanı</label>\r\n\t\t\t\t\t\t\t\t\t\t<select class=\"js-example-basic-multiple form-control-sm\" name=\"danisman\" id=\"danisman\" required style=\"width:100%\">\r\n\t\t\t\t\t\t\t\t\t<option value=\"0\" ";
echo $Sonuc["danisman"] == 0 ? "selected" : "";
echo ">Bu Seçeneği Kullanmayacağım</option>\r\n\t\t\t\t\t\t\t\t\t";
$DANISMANSorgu = $db->prepare("SELECT * FROM ekibimiz ORDER BY sira ASC");
$DANISMANSorgu->execute();
$DANISMANislem = $DANISMANSorgu->fetchALL(PDO::FETCH_ASSOC);
echo "\t\t\t\t\t\t\t\t\t";
foreach ($DANISMANislem as $DANISMANSonuc) {
    echo "\t\t\t\t\t\t\t\t\t\t<option value=\"";
    echo $DANISMANSonuc["id"];
    echo "\" ";
    echo $Sonuc["danisman"] == $DANISMANSonuc["id"] ? "selected" : "";
    echo ">";
    echo $DANISMANSonuc["adi"];
    echo "</option>\r\n\t\t\t\t\t\t\t\t\t";
}
echo "\t\t\r\n\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"video\">İlan Video (<a href=\"images/video.png\" target=\"_blank\">Youtube Link id ?</a>)</label>\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"video\" id=\"video\" value=\"";
echo isset($_GET["islem"]) == "duzenle" ? $Sonuc["video"] : "";
echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-6\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"brut\">m² (Brüt) <i class=\"icon-info text-info\" data-toggle=\"popover\" data-content=\"Bu Seçeneği Kullanmayacaksanız Boş Bırakabilirsiniz.!\" data-trigger=\"hover\"></i></label>\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"brut\" id=\"brut\" value=\"";
echo isset($_GET["islem"]) == "duzenle" ? $Sonuc["brut"] : "";
echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-6\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"net\">m² (Net) <i class=\"icon-info text-info\" data-toggle=\"popover\" data-content=\"Bu Seçeneği Kullanmayacaksanız Boş Bırakabilirsiniz.!\" data-trigger=\"hover\"></i></label>\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"net\" id=\"net\" value=\"";
echo isset($_GET["islem"]) == "duzenle" ? $Sonuc["net"] : "";
echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"oda\">Oda Sayısı</label>\r\n\t\t\t\t\t\t\t\t\t\t<select class=\"form-control w-100\" name=\"oda\" id=\"oda\" required>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"0\" ";
echo $Sonuc["oda"] == 0 ? "selected" : "";
echo ">Bu Seçeneği Kullanmayacağım</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Stüdyo 1+0\" ";
echo $Sonuc["oda"] == "Stüdyo 1+0" ? "selected" : "";
echo ">Stüdyo 1+0</option>\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"1+1\" ";
echo $Sonuc["oda"] == "1+1" ? "selected" : "";
echo ">1+1</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"1.5+1\" ";
echo $Sonuc["oda"] == "1.5+1" ? "selected" : "";
echo ">1.5+1</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"2+0\" ";
echo $Sonuc["oda"] == "2+0" ? "selected" : "";
echo ">2+0</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"2+1\" ";
echo $Sonuc["oda"] == "2+1" ? "selected" : "";
echo ">2+1</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"2.5+1\" ";
echo $Sonuc["oda"] == "2.5+1" ? "selected" : "";
echo ">2.5+1</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"2+2\" ";
echo $Sonuc["oda"] == "2+2" ? "selected" : "";
echo ">2+2</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"3+1\" ";
echo $Sonuc["oda"] == "3+1" ? "selected" : "";
echo ">3+1</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"3.5+1\" ";
echo $Sonuc["oda"] == "3.5+1" ? "selected" : "";
echo ">3.5+1</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"3+2\" ";
echo $Sonuc["oda"] == "3+2" ? "selected" : "";
echo ">3+2</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"4+1\" ";
echo $Sonuc["oda"] == "4+1" ? "selected" : "";
echo ">4+1</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"4.5+1\" ";
echo $Sonuc["oda"] == "4.5+1" ? "selected" : "";
echo ">4.5+1</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"4+2\" ";
echo $Sonuc["oda"] == "4+2" ? "selected" : "";
echo ">4+2</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"4+3\" ";
echo $Sonuc["oda"] == "4+3" ? "selected" : "";
echo ">4+3</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"4+4\" ";
echo $Sonuc["oda"] == "4+4" ? "selected" : "";
echo ">4+4</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"5+1\" ";
echo $Sonuc["oda"] == "5+1" ? "selected" : "";
echo ">5+1</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"5+2\" ";
echo $Sonuc["oda"] == "5+2" ? "selected" : "";
echo ">5+2</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"5+3\" ";
echo $Sonuc["oda"] == "5+3" ? "selected" : "";
echo ">5+3</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"5+4\" ";
echo $Sonuc["oda"] == "5+4" ? "selected" : "";
echo ">5+4</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"6+1\" ";
echo $Sonuc["oda"] == "6+1" ? "selected" : "";
echo ">6+1</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"6+2\" ";
echo $Sonuc["oda"] == "6+2" ? "selected" : "";
echo ">6+2</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"6+3\" ";
echo $Sonuc["oda"] == "6+3" ? "selected" : "";
echo ">6+3</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"7+1\" ";
echo $Sonuc["oda"] == "7+1" ? "selected" : "";
echo ">7+1</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"7+2\" ";
echo $Sonuc["oda"] == "7+2" ? "selected" : "";
echo ">7+2</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"7+3\" ";
echo $Sonuc["oda"] == "7+3" ? "selected" : "";
echo ">7+3</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"8+1\" ";
echo $Sonuc["oda"] == "8+1" ? "selected" : "";
echo ">8+1</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"8+2\" ";
echo $Sonuc["oda"] == "8+2" ? "selected" : "";
echo ">8+2</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"8+3\" ";
echo $Sonuc["oda"] == "8+3" ? "selected" : "";
echo ">8+3</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"8+4\" ";
echo $Sonuc["oda"] == "8+4" ? "selected" : "";
echo ">8+4</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"9+1\" ";
echo $Sonuc["oda"] == "9+1" ? "selected" : "";
echo ">9+1</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"9+2\" ";
echo $Sonuc["oda"] == "9+2" ? "selected" : "";
echo ">9+2</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"9+3\" ";
echo $Sonuc["oda"] == "9+3" ? "selected" : "";
echo ">9+3</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"9+4\" ";
echo $Sonuc["oda"] == "9+4" ? "selected" : "";
echo ">9+4</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"9+5\" ";
echo $Sonuc["oda"] == "9+5" ? "selected" : "";
echo ">9+5</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"9+6\" ";
echo $Sonuc["oda"] == "9+6" ? "selected" : "";
echo ">9+6</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"10+1\" ";
echo $Sonuc["oda"] == "10+1" ? "selected" : "";
echo ">10+1</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"10+2\" ";
echo $Sonuc["oda"] == "10+2" ? "selected" : "";
echo ">10+2</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"10 Üzeri\" ";
echo $Sonuc["oda"] == "10 Üzeri" ? "selected" : "";
echo ">10 Üzeri</option>\t\t \t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"katsayisi\">Kat Sayısı</label>\r\n\t\t\t\t\t\t\t\t\t\t<select class=\"form-control w-100\" name=\"katsayisi\" id=\"katsayisi\" required>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"0\" ";
echo $Sonuc["katsayisi"] == 0 ? "selected" : "";
echo ">Bu Seçeneği Kullanmayacağım</option>\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\" ";
echo $Sonuc["katsayisi"] == "1" ? "selected" : "";
echo ">1</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"2\" ";
echo $Sonuc["katsayisi"] == "2" ? "selected" : "";
echo ">2</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"3\" ";
echo $Sonuc["katsayisi"] == "3" ? "selected" : "";
echo ">3</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"4\" ";
echo $Sonuc["katsayisi"] == "4" ? "selected" : "";
echo ">4</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"5\" ";
echo $Sonuc["katsayisi"] == "5" ? "selected" : "";
echo ">5</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"6\" ";
echo $Sonuc["katsayisi"] == "6" ? "selected" : "";
echo ">6</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"7\" ";
echo $Sonuc["katsayisi"] == "7" ? "selected" : "";
echo ">7</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"8\" ";
echo $Sonuc["katsayisi"] == "8" ? "selected" : "";
echo ">8</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"9\" ";
echo $Sonuc["katsayisi"] == "9" ? "selected" : "";
echo ">9</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"10\" ";
echo $Sonuc["katsayisi"] == "10" ? "selected" : "";
echo ">10</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"11\" ";
echo $Sonuc["katsayisi"] == "11" ? "selected" : "";
echo ">11</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"12\" ";
echo $Sonuc["katsayisi"] == "12" ? "selected" : "";
echo ">12</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"13\" ";
echo $Sonuc["katsayisi"] == "13" ? "selected" : "";
echo ">13</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"14\" ";
echo $Sonuc["katsayisi"] == "14" ? "selected" : "";
echo ">14</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"15\" ";
echo $Sonuc["katsayisi"] == "15" ? "selected" : "";
echo ">15</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"16\" ";
echo $Sonuc["katsayisi"] == "16" ? "selected" : "";
echo ">16</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"17\" ";
echo $Sonuc["katsayisi"] == "17" ? "selected" : "";
echo ">17</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"18\" ";
echo $Sonuc["katsayisi"] == "18" ? "selected" : "";
echo ">18</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"19\" ";
echo $Sonuc["katsayisi"] == "19" ? "selected" : "";
echo ">19</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"20\" ";
echo $Sonuc["katsayisi"] == "20" ? "selected" : "";
echo ">20</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"21\" ";
echo $Sonuc["katsayisi"] == "21" ? "selected" : "";
echo ">21</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"22\" ";
echo $Sonuc["katsayisi"] == "22" ? "selected" : "";
echo ">22</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"23\" ";
echo $Sonuc["katsayisi"] == "23" ? "selected" : "";
echo ">23</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"24\" ";
echo $Sonuc["katsayisi"] == "24" ? "selected" : "";
echo ">24</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"25\" ";
echo $Sonuc["katsayisi"] == "25" ? "selected" : "";
echo ">25</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"26\" ";
echo $Sonuc["katsayisi"] == "26" ? "selected" : "";
echo ">26</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"27\" ";
echo $Sonuc["katsayisi"] == "27" ? "selected" : "";
echo ">27</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"28\" ";
echo $Sonuc["katsayisi"] == "28" ? "selected" : "";
echo ">28</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"29\" ";
echo $Sonuc["katsayisi"] == "29" ? "selected" : "";
echo ">29</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"30 ve üzeri\" ";
echo $Sonuc["katsayisi"] == "30 ve üzeri" ? "selected" : "";
echo ">30 ve üzeri</option>\t \t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"bulundugukat\">Bulunduğu Kat</label>\r\n\t\t\t\t\t\t\t\t\t\t<select class=\"form-control w-100\" name=\"bulundugukat\" id=\"bulundugukat\" required>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"0\" ";
echo $Sonuc["bulundugukat"] == 0 ? "selected" : "";
echo ">Bu Seçeneği Kullanmayacağım</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Kot 4\" ";
echo $Sonuc["bulundugukat"] == "Kot 4" ? "selected" : "";
echo ">Kot 4</option>\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Kot 3\" ";
echo $Sonuc["bulundugukat"] == "Kot 3" ? "selected" : "";
echo ">3</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Kot 2\" ";
echo $Sonuc["bulundugukat"] == "Kot 2" ? "selected" : "";
echo ">Kot 2</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Kot 1\" ";
echo $Sonuc["bulundugukat"] == "Kot 1" ? "selected" : "";
echo ">Kot 1</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Bodrum Kat\" ";
echo $Sonuc["bulundugukat"] == "Bodrum Kat" ? "selected" : "";
echo ">Bodrum Kat</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Zemin Kat\" ";
echo $Sonuc["bulundugukat"] == "Zemin Kat" ? "selected" : "";
echo ">Zemin Kat</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Bahçe Katı\" ";
echo $Sonuc["bulundugukat"] == "Bahçe Katı" ? "selected" : "";
echo ">Bahçe Katı</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Giriş Katı\" ";
echo $Sonuc["bulundugukat"] == "Giriş Katı" ? "selected" : "";
echo ">Giriş Katı</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Yüksek Giriş\" ";
echo $Sonuc["bulundugukat"] == "Yüksek Giriş" ? "selected" : "";
echo ">Yüksek Giriş</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Müstakil\" ";
echo $Sonuc["bulundugukat"] == "Müstakil" ? "selected" : "";
echo ">Müstakil</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Villa Tipi\" ";
echo $Sonuc["bulundugukat"] == "Villa Tipi" ? "selected" : "";
echo ">Villa Tipi</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Çatı Katı\" ";
echo $Sonuc["bulundugukat"] == "Çatı Katı" ? "selected" : "";
echo ">Çatı Katı</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\" ";
echo $Sonuc["bulundugukat"] == "1" ? "selected" : "";
echo ">1</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"2\" ";
echo $Sonuc["bulundugukat"] == "2" ? "selected" : "";
echo ">2</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"3\" ";
echo $Sonuc["bulundugukat"] == "3" ? "selected" : "";
echo ">3</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"4\" ";
echo $Sonuc["bulundugukat"] == "4" ? "selected" : "";
echo ">4</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"5\" ";
echo $Sonuc["bulundugukat"] == "5" ? "selected" : "";
echo ">5</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"6\" ";
echo $Sonuc["bulundugukat"] == "6" ? "selected" : "";
echo ">6</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"7\" ";
echo $Sonuc["bulundugukat"] == "7" ? "selected" : "";
echo ">7</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"8\" ";
echo $Sonuc["bulundugukat"] == "8" ? "selected" : "";
echo ">8</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"9\" ";
echo $Sonuc["bulundugukat"] == "9" ? "selected" : "";
echo ">9</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"10\" ";
echo $Sonuc["bulundugukat"] == "10" ? "selected" : "";
echo ">10</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"11\" ";
echo $Sonuc["bulundugukat"] == "11" ? "selected" : "";
echo ">11</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"12\" ";
echo $Sonuc["bulundugukat"] == "12" ? "selected" : "";
echo ">12</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"13\" ";
echo $Sonuc["bulundugukat"] == "13" ? "selected" : "";
echo ">13</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"14\" ";
echo $Sonuc["bulundugukat"] == "14" ? "selected" : "";
echo ">14</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"15\" ";
echo $Sonuc["bulundugukat"] == "15" ? "selected" : "";
echo ">15</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"16\" ";
echo $Sonuc["bulundugukat"] == "16" ? "selected" : "";
echo ">16</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"17\" ";
echo $Sonuc["bulundugukat"] == "17" ? "selected" : "";
echo ">17</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"18\" ";
echo $Sonuc["bulundugukat"] == "18" ? "selected" : "";
echo ">18</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"19\" ";
echo $Sonuc["bulundugukat"] == "19" ? "selected" : "";
echo ">19</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"20\" ";
echo $Sonuc["bulundugukat"] == "20" ? "selected" : "";
echo ">20</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"21\" ";
echo $Sonuc["bulundugukat"] == "21" ? "selected" : "";
echo ">21</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"22\" ";
echo $Sonuc["bulundugukat"] == "22" ? "selected" : "";
echo ">22</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"23\" ";
echo $Sonuc["bulundugukat"] == "23" ? "selected" : "";
echo ">23</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"24\" ";
echo $Sonuc["bulundugukat"] == "24" ? "selected" : "";
echo ">24</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"25\" ";
echo $Sonuc["bulundugukat"] == "25" ? "selected" : "";
echo ">25</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"26\" ";
echo $Sonuc["bulundugukat"] == "26" ? "selected" : "";
echo ">26</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"27\" ";
echo $Sonuc["bulundugukat"] == "27" ? "selected" : "";
echo ">27</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"28\" ";
echo $Sonuc["bulundugukat"] == "28" ? "selected" : "";
echo ">28</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"29\" ";
echo $Sonuc["bulundugukat"] == "29" ? "selected" : "";
echo ">29</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"30 ve üzeri\" ";
echo $Sonuc["bulundugukat"] == "30 ve üzeri" ? "selected" : "";
echo ">30 ve üzeri</option>\t \t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"bina\">Bina Yaşı</label>\r\n\t\t\t\t\t\t\t\t\t\t<select class=\"form-control w-100\" name=\"bina\" id=\"bina\" required>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"0\" ";
echo $Sonuc["bina"] == 0 ? "selected" : "";
echo ">Bu Seçeneği Kullanmayacağım</option>\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\" ";
echo $Sonuc["bina"] == "1" ? "selected" : "";
echo ">1</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"2\" ";
echo $Sonuc["bina"] == "2" ? "selected" : "";
echo ">2</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"3\" ";
echo $Sonuc["bina"] == "3" ? "selected" : "";
echo ">3</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"4\" ";
echo $Sonuc["bina"] == "4" ? "selected" : "";
echo ">4</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"5-10 arası\" ";
echo $Sonuc["bina"] == "5-10 arası" ? "selected" : "";
echo ">5-10 arası</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"11-15 arası\" ";
echo $Sonuc["bina"] == "11-15 arası" ? "selected" : "";
echo ">11-15 arası</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"16-20 arası\" ";
echo $Sonuc["bina"] == "16-20 arası" ? "selected" : "";
echo ">16-20 arası</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"21-25 arası\" ";
echo $Sonuc["bina"] == "21-25 arası" ? "selected" : "";
echo ">21-25 arası</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"26-30 arası\" ";
echo $Sonuc["bina"] == "26-30 arası" ? "selected" : "";
echo ">26-30 arası</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"31 ve üzeri\" ";
echo $Sonuc["bina"] == "31 ve üzeri" ? "selected" : "";
echo ">31 ve üzeri</option>\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"isitma\">Isıtma</label>\r\n\t\t\t\t\t\t\t\t\t\t<select class=\"form-control w-100\" name=\"isitma\" id=\"isitma\" required>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"0\" ";
echo $Sonuc["isitma"] == 0 ? "selected" : "";
echo ">Bu Seçeneği Kullanmayacağım</option>\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Yok\" ";
echo $Sonuc["isitma"] == "Yok" ? "selected" : "";
echo ">Yok</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Soba\" ";
echo $Sonuc["isitma"] == "Soba" ? "selected" : "";
echo ">Soba</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Doğalgaz Sobası\" ";
echo $Sonuc["isitma"] == "Doğalgaz Sobası" ? "selected" : "";
echo ">Doğalgaz Sobası</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Kat Kaloriferi\" ";
echo $Sonuc["isitma"] == "Kat Kaloriferi" ? "selected" : "";
echo ">Kat Kaloriferi</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Merkezi\" ";
echo $Sonuc["isitma"] == "Merkezi" ? "selected" : "";
echo ">Merkezi</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Merkezi (Pay Ölçer)\" ";
echo $Sonuc["isitma"] == "Merkezi (Pay Ölçer)" ? "selected" : "";
echo ">Merkezi (Pay Ölçer)</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Doğalgaz (Kombi)\" ";
echo $Sonuc["isitma"] == "Doğalgaz (Kombi)" ? "selected" : "";
echo ">Doğalgaz (Kombi)</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Yerden Isıtma\" ";
echo $Sonuc["isitma"] == "Yerden Isıtma" ? "selected" : "";
echo ">Yerden Isıtma</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Klima\" ";
echo $Sonuc["isitma"] == "Klima" ? "selected" : "";
echo ">Klima</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Fancoil Ünitesi\" ";
echo $Sonuc["isitma"] == "Fancoil Ünitesi" ? "selected" : "";
echo ">Fancoil Ünitesi</option>\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Güneş Enerjisi\" ";
echo $Sonuc["isitma"] == "Güneş Enerjisi" ? "selected" : "";
echo ">Güneş Enerjisi</option>\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Jeotermal\" ";
echo $Sonuc["isitma"] == "Jeotermal" ? "selected" : "";
echo ">Jeotermal</option>\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Şömine\" ";
echo $Sonuc["isitma"] == "Şömine" ? "selected" : "";
echo ">Şömine</option>\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"VRV\" ";
echo $Sonuc["isitma"] == "VRV" ? "selected" : "";
echo ">VRV</option>\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Isı Pompası\" ";
echo $Sonuc["isitma"] == "Isı Pompası" ? "selected" : "";
echo ">Isı Pompası</option>\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"banyo\">Banyo Sayısı</label>\r\n\t\t\t\t\t\t\t\t\t\t<select class=\"form-control w-100\" name=\"banyo\" id=\"banyo\" required>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"0\" ";
echo $Sonuc["banyo"] == 0 ? "selected" : "";
echo ">Bu Seçeneği Kullanmayacağım</option>\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\" ";
echo $Sonuc["banyo"] == "1" ? "selected" : "";
echo ">1</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"2\" ";
echo $Sonuc["banyo"] == "2" ? "selected" : "";
echo ">2</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"3\" ";
echo $Sonuc["banyo"] == "3" ? "selected" : "";
echo ">3</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"4\" ";
echo $Sonuc["banyo"] == "4" ? "selected" : "";
echo ">4</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"5\" ";
echo $Sonuc["banyo"] == "5" ? "selected" : "";
echo ">5</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"6\" ";
echo $Sonuc["banyo"] == "6" ? "selected" : "";
echo ">6</option>\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"6 ve üzeri\" ";
echo $Sonuc["banyo"] == "6 ve üzeri" ? "selected" : "";
echo ">6 ve üzeri</option>\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"balkon\">Balkon</label>\r\n\t\t\t\t\t\t\t\t\t\t<select class=\"form-control w-100\" name=\"balkon\" id=\"balkon\" required>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"0\" ";
echo $Sonuc["balkon"] == 0 ? "selected" : "";
echo ">Bu Seçeneği Kullanmayacağım</option>\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Var\" ";
echo $Sonuc["balkon"] == "Var" ? "selected" : "";
echo ">Var</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Yok\" ";
echo $Sonuc["balkon"] == "Yok" ? "selected" : "";
echo ">Yok</option>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"esya\">Eşya Durumu</label>\r\n\t\t\t\t\t\t\t\t\t\t<select class=\"form-control w-100\" name=\"esya\" id=\"esya\">\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"0\" ";
echo $Sonuc["esya"] == 0 ? "selected" : "";
echo ">Bu Seçeneği Kullanmayacağım</option>\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Eşyalı\" ";
echo $Sonuc["esya"] == "Eşyalı" ? "selected" : "";
echo ">Eşyalı</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Eşyasız\" ";
echo $Sonuc["esya"] == "Eşyasız" ? "selected" : "";
echo ">Eşyasız</option>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"row\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"kdrumu\">Kullanım Durumu</label>\r\n\t\t\t\t\t\t\t\t\t\t<select class=\"form-control w-100\" name=\"kdrumu\" id=\"kdrumu\">\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"0\" ";
echo $Sonuc["kdrumu"] == 0 ? "selected" : "";
echo ">Bu Seçeneği Kullanmayacağım</option>\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Boş\" ";
echo $Sonuc["kdrumu"] == "Boş" ? "selected" : "";
echo ">Boş</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Kiracılı\" ";
echo $Sonuc["kdrumu"] == "Kiracılı" ? "selected" : "";
echo ">Kiracılı</option>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Mülk Sahibi\" ";
echo $Sonuc["kdrumu"] == "Mülk Sahibi" ? "selected" : "";
echo ">Mülk Sahibi</option>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"takas\">Takaslı</label>\r\n\t\t\t\t\t\t\t\t\t\t<select class=\"form-control w-100\" name=\"takas\" id=\"takas\" required>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"0\" ";
echo $Sonuc["takas"] == 0 ? "selected" : "";
echo ">Bu Seçeneği Kullanmayacağım</option>\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Evet\" ";
echo $Sonuc["takas"] == "Evet" ? "selected" : "";
echo ">Evet</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Hayır\" ";
echo $Sonuc["takas"] == "Hayır" ? "selected" : "";
echo ">Hayır</option>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t</div>\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"krediu\">Krediye Uygun mu ?</label>\r\n\t\t\t\t\t\t\t\t\t\t<select class=\"form-control w-100\" name=\"krediu\" id=\"krediu\" required>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"0\" ";
echo $Sonuc["krediu"] == 0 ? "selected" : "";
echo ">Bu Seçeneği Kullanmayacağım</option>\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Evet\" ";
echo $Sonuc["krediu"] == "Evet" ? "selected" : "";
echo ">Evet</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Hayır\" ";
echo $Sonuc["krediu"] == "Hayır" ? "selected" : "";
echo ">Hayır</option>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"garama\">Görüntülü Arama İle Gezilebilir</label>\r\n\t\t\t\t\t\t\t\t\t\t<select class=\"form-control w-100\" name=\"garama\" id=\"garama\" required>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"0\" ";
echo $Sonuc["garama"] == 0 ? "selected" : "";
echo ">Bu Seçeneği Kullanmayacağım</option>\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Evet\" ";
echo $Sonuc["garama"] == "Evet" ? "selected" : "";
echo ">Evet</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Hayır\" ";
echo $Sonuc["garama"] == "Hayır" ? "selected" : "";
echo ">Hayır</option>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"row\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"imardurumu\">İmar Durumu</label>\r\n\t\t\t\t\t\t\t\t\t\t<select class=\"form-control w-100\" name=\"imardurumu\" id=\"imardurumu\" required>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"0\" ";
echo $Sonuc["imardurumu"] == 0 ? "selected" : "";
echo ">Bu Seçeneği Kullanmayacağım</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Ada\" ";
echo $Sonuc["imardurumu"] == "Ada" ? "selected" : "";
echo ">Ada</option>\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"A-Lejantlı\" ";
echo $Sonuc["imardurumu"] == "A-Lejantlı" ? "selected" : "";
echo ">A-Lejantlı</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Arazi\" ";
echo $Sonuc["imardurumu"] == "€" ? "selected" : "";
echo ">Arazi</option>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Bağ & Bahçe\" ";
echo $Sonuc["imardurumu"] == "£" ? "selected" : "";
echo ">Bağ & Bahçe</option>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Depo & Antrepo\" ";
echo $Sonuc["imardurumu"] == "Depo & Antrepo" ? "selected" : "";
echo ">Depo & Antrepo</option>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Eğitim\" ";
echo $Sonuc["imardurumu"] == "Eğitim" ? "selected" : "";
echo ">Eğitim</option>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Enerji Depolama\" ";
echo $Sonuc["imardurumu"] == "Enerji Depolama" ? "selected" : "";
echo ">Enerji Depolama</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Konut\" ";
echo $Sonuc["imardurumu"] == "Konut" ? "selected" : "";
echo ">Konut</option>\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Muhtelif\" ";
echo $Sonuc["imardurumu"] == "Muhtelif" ? "selected" : "";
echo ">Muhtelif</option>\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Özel Kullanım\" ";
echo $Sonuc["imardurumu"] == "Özel Kullanım" ? "selected" : "";
echo ">Özel Kullanım</option>\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Sağlık\" ";
echo $Sonuc["imardurumu"] == "Sağlık" ? "selected" : "";
echo ">Sağlık</option>\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Sanayi\" ";
echo $Sonuc["imardurumu"] == "Sanayi" ? "selected" : "";
echo ">Sanayi</option>\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Sera\" ";
echo $Sonuc["imardurumu"] == "Sera" ? "selected" : "";
echo ">Sera</option>\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Sit Alanı\" ";
echo $Sonuc["imardurumu"] == "Sit Alanı" ? "selected" : "";
echo ">Sit Alanı</option>\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Spor Alanı\" ";
echo $Sonuc["imardurumu"] == "Spor Alanı" ? "selected" : "";
echo ">Spor Alanı</option>\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Tarla\" ";
echo $Sonuc["imardurumu"] == "Tarla" ? "selected" : "";
echo ">Tarla</option>\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Ticari\" ";
echo $Sonuc["imardurumu"] == "Ticari" ? "selected" : "";
echo ">Ticari</option>\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Ticari + Konut\" ";
echo $Sonuc["imardurumu"] == "Ticari + Konut" ? "selected" : "";
echo ">Ticari + Konut</option>\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Toplu Konut\" ";
echo $Sonuc["imardurumu"] == "Toplu Konut" ? "selected" : "";
echo ">Toplu Konut</option>\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Turizm\" ";
echo $Sonuc["imardurumu"] == "Turizm" ? "selected" : "";
echo ">Turizm</option>\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Turizm + Konut\" ";
echo $Sonuc["imardurumu"] == "Turizm + Konut" ? "selected" : "";
echo ">Turizm + Konut</option>\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Villa\" ";
echo $Sonuc["imardurumu"] == "Villa" ? "selected" : "";
echo ">Villa</option>\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Zeytinlik\" ";
echo $Sonuc["imardurumu"] == "Zeytinlik" ? "selected" : "";
echo ">Zeytinlik</option>\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"adano\">Ada No <i class=\"icon-info text-info\" data-toggle=\"popover\" data-content=\"Bu Seçeneği Kullanmayacaksanız Boş Bırakabilirsiniz.!\" data-trigger=\"hover\"></i></label>\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"adano\" value=\"";
echo $Sonuc["adano"];
echo "\">\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"parselno\">Parsel No <i class=\"icon-info text-info\" data-toggle=\"popover\" data-content=\"Bu Seçeneği Kullanmayacaksanız Boş Bırakabilirsiniz.!\" data-trigger=\"hover\"></i></label>\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"parselno\" value=\"";
echo $Sonuc["parselno"];
echo "\">\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"paftano\">Pafta No <i class=\"icon-info text-info\" data-toggle=\"popover\" data-content=\"Bu Seçeneği Kullanmayacaksanız Boş Bırakabilirsiniz.!\" data-trigger=\"hover\"></i></label>\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"paftano\" value=\"";
echo $Sonuc["paftano"];
echo "\">\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"kaks\">Kaks (Emsal) <i class=\"icon-info text-info\" data-toggle=\"popover\" data-content=\"Bu Seçeneği Kullanmayacaksanız Boş Bırakabilirsiniz.!\" data-trigger=\"hover\"></i></label>\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"kaks\" value=\"";
echo $Sonuc["kaks"];
echo "\">\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"gabari\">Gabari <i class=\"icon-info text-info\" data-toggle=\"popover\" data-content=\"Bu Seçeneği Kullanmayacaksanız Boş Bırakabilirsiniz.!\" data-trigger=\"hover\"></i></label>\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"gabari\" value=\"";
echo $Sonuc["gabari"];
echo "\">\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"tapudurumu\">Tapu Durumu <i class=\"icon-info text-info\" data-toggle=\"popover\" data-content=\"Bu Seçeneği Kullanmayacaksanız Boş Bırakabilirsiniz.!\" data-trigger=\"hover\"></i></label>\r\n\t\t\t\t\t\t\t\t\t\t<select class=\"form-control w-100\" name=\"tapudurumu\" id=\"tapudurumu\" required>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"0\" ";
echo $Sonuc["tapudurumu"] == 0 ? "selected" : "";
echo ">Bu Seçeneği Kullanmayacağım</option>\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Hisseli Tapu\" ";
echo $Sonuc["tapudurumu"] == "Hisseli Tapu" ? "selected" : "";
echo ">Hisseli Tapu</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Müstakil Parsel\" ";
echo $Sonuc["tapudurumu"] == "Müstakil Parsel" ? "selected" : "";
echo ">Müstakil Parsel</option>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Tahsis\" ";
echo $Sonuc["tapudurumu"] == "Tahsis" ? "selected" : "";
echo ">Tahsis</option>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Zilliyet\" ";
echo $Sonuc["tapudurumu"] == "Zilliyet" ? "selected" : "";
echo ">Zilliyet</option>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t</div>\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"katkarsiligi\">Kat Karşılığı</label>\r\n\t\t\t\t\t\t\t\t\t\t<select class=\"form-control w-100\" name=\"katkarsiligi\" id=\"katkarsiligi\" required>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"0\" ";
echo $Sonuc["katkarsiligi"] == 0 ? "selected" : "";
echo ">Bu Seçeneği Kullanmayacağım</option>\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Evet\" ";
echo $Sonuc["katkarsiligi"] == "Evet" ? "selected" : "";
echo ">Evet</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"Hayır\" ";
echo $Sonuc["katkarsiligi"] == "Hayır" ? "selected" : "";
echo ">Hayır</option>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t \r\n\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t<label>Fiyat <i class=\"icon-info text-info\" data-toggle=\"popover\" data-content=\"Emlak İlan Para Birimi Geçerli Olacaktır.!\" data-trigger=\"hover\"></i></label>\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"fiyat\" value=\"";
echo $Sonuc["fiyat"];
echo "\">\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"aidat\">Adiat <i class=\"icon-info text-info\" data-toggle=\"popover\" data-content=\"Bu Seçeneği Kullanmayacaksanız Boş Bırakabilirsiniz.! Emlak İlan Para Birimi Geçerli Olacaktır.!\" data-trigger=\"hover\"></i></label>\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"aidat\" value=\"";
echo $Sonuc["aidat"];
echo "\">\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t<label>Depozito <i class=\"icon-info text-info\" data-toggle=\"popover\" data-content=\"Bu Seçeneği Kullanmayacaksanız Boş Bırakabilirsiniz.! Emlak İlan Para Birimi Geçerli Olacaktır.!\" data-trigger=\"hover\"></i></label>\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"depozito\" value=\"";
echo $Sonuc["depozito"];
echo "\">\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"pbirim\">Para Birimi</label>\r\n\t\t\t\t\t\t\t\t\t\t<select class=\"form-control w-100\" name=\"pbirim\" id=\"pbirim\" required>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"TL\" ";
echo $Sonuc["pbirim"] == "₺" ? "selected" : "";
echo ">TL</option>\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"\$\" ";
echo $Sonuc["pbirim"] == "\$" ? "selected" : "";
echo ">\$</option>\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"€\" ";
echo $Sonuc["pbirim"] == "€" ? "selected" : "";
echo ">€</option>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"£\" ";
echo $Sonuc["pbirim"] == "£" ? "selected" : "";
echo ">£</option>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<option value=\"AZN\" ";
echo $Sonuc["pbirim"] == "AZN" ? "selected" : "";
echo ">AZN</option>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group col-sm-4\">\r\n\t\t\t\t\t\t\t\t<label>İl</label>\r\n\t\t\t\t\t\t\t\t<select name=\"il\" id=\"il\" class=\"form-control\" onchange=\"findAddress();return false\">\r\n\t\t\t\t\t\t\t\t\t";
$ILSorgu = $db->prepare("SELECT * FROM il ORDER BY id ASC");
$ILSorgu->execute();
$ILislem = $ILSorgu->fetchALL(PDO::FETCH_ASSOC);
echo "\t\t\t\t\t\t\t\t\t";
foreach ($ILislem as $ILSonuc) {
    echo "\t\t\t\t\t\t\t\t\t\t<option value=\"";
    echo $ILSonuc["id"];
    echo "\" data-foo=\"";
    echo $ILSonuc["il_adi"];
    echo "\" ";
    echo $Sonuc["il"] == $ILSonuc["id"] ? "selected" : "";
    echo ">";
    echo $ILSonuc["il_adi"];
    echo "</option>\r\n\t\t\t\t\t\t\t\t\t";
}
echo "\t\r\n\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t<div class=\"form-group col-sm-4\">\r\n\t\t\t\t\t\t\t\t<label>İlçe</label>\r\n\t\t\t\t\t\t\t\t<select class=\"form-control w-100\" name=\"ilce\" id=\"ilce\" onchange=\"findAddress2();return false\">\r\n\t\t\t\t\t\t\t\t<option>İlçe Seçiniz</option>\r\n\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t<div class=\"form-group col-sm-4\">\r\n\t\t\t\t\t\t\t\t<label>Semt / Mahalle</label>\r\n\t\t\t\t\t\t\t\t<select class=\"form-control w-100\" name=\"semt\" id=\"semt\" onchange=\"findAddress3();return false\">\r\n\t\t\t\t\t\t\t\t<option>Seçiniz</option>\r\n\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<script>\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\tymaps.ready(init);\r\n\t\t\t\t\t\t\t\tvar myMap;\r\n\r\n\t\t\t\t\t\t\t\tfunction init () {\r\n\t\t\t\t\t\t\t\t\tmyMap = new ymaps.Map(\"map\", {\r\n\t\t\t\t\t\t\t\t\t\t";
if ($_GET["islem"] == "duzenle") {
    echo "\t\t\t\t\t\t\t\t\t\t";
    if ($Sonuc["latfield"] == "") {
        echo "\t\t\t\t\t\t\t\t\t\tcenter: [";
        echo $ayar["latfield"];
        echo ", ";
        echo $ayar["lngfield"];
        echo "],\r\n\t\t\t\t\t\t\t\t\t\tzoom: ";
        echo $ayar["zoom"];
        echo "\t\t\t\t\t\t\t\t\t\t";
    } else {
        echo "\t\t\t\t\t\t\t\t\t\tcenter: [";
        echo $Sonuc["latfield"];
        echo ", ";
        echo $Sonuc["lngfield"];
        echo "],\r\n\t\t\t\t\t\t\t\t\t\tzoom: ";
        echo $Sonuc["zoom"];
        echo "\t\t\t\t\t\t\t\t\t\t";
    }
    echo "\t\t\t\t\t\t\t\t\t\t";
} else {
    echo "\t\t\t\t\t\t\t\t\t   center: [";
    echo $ayar["latfield"];
    echo ", ";
    echo $ayar["lngfield"];
    echo "],\r\n\t\t\t\t\t\t\t\t\t\tzoom: ";
    echo $ayar["zoom"];
    echo "\t\t\t\t\t\t\t\t\t\t";
}
echo "\t\t\t\t\t\t\t\t\t}, \r\n\t\t\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\t\t\tballoonMaxWidth: 200,\r\n\t\t\t\t\t\t\t\t\t\tsearchControlProvider: 'yandex#search'\r\n\t\t\t\t\t\t\t\t\t});\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t";
if ($_GET["islem"] == "duzenle") {
    echo "\t\t\t\t\t\t\t\t\t myPlacemark1 = new ymaps.Placemark([";
    echo $Sonuc["latfield"];
    echo ", ";
    echo $Sonuc["lngfield"];
    echo "], {\r\n\t\t\t\t\t\t\t\t\t\t ";
} else {
    echo "\t\t\t\t\t\t\t\t\t\t myPlacemark1 = new ymaps.Placemark([";
    echo $ayar["latfield"];
    echo ", ";
    echo $ayar["lngfield"];
    echo "], {\r\n\t\t\t\t\t\t\t\t\t\t\t ";
}
echo "\t\t\t\t\t\t\t\t\t\t\tballoonContent: '";
echo tirnak($Sonuc["adi"]);
echo "'\r\n\t\t\t\t\t\t\t\t\t\t}, {\r\n\t\t\t\t\t\t\t\t\t\t\ticonLayout: 'default#image',\r\n\t\t\t\t\t\t\t\t\t\t\ticonImageClipRect: [[69,0], [97, 46]],\r\n\t\t\t\t\t\t\t\t\t\t\ticonImageHref: 'images/sprite.png',\r\n\t\t\t\t\t\t\t\t\t\t\ticonImageSize: [35, 63],\r\n\t\t\t\t\t\t\t\t\t\t\ticonImageOffset: [-35, -63]\r\n\t\t\t\t\t\t\t\t\t\t}),\r\n\r\n\t\t\t\t\t\t\t\t\t/**\r\n\t\t\t\t\t\t\t\t\t * Processing events that occur when the user\r\n\t\t\t\t\t\t\t\t\t * left-clicks anywhere on the map.\r\n\t\t\t\t\t\t\t\t\t * When such an event occurs, we open the balloon.\r\n\t\t\t\t\t\t\t\t\t */\r\n\t\t\t\t\t\t\t\t\tmyMap.events.add('click', function (e) {\r\n\t\t\t\t\t\t\t\t\t\tif (!myMap.balloon.isOpen()) {\r\n\t\t\t\t\t\t\t\t\t\t\tvar coords = e.get('coords');\r\n\t\t\t\t\t\t\t\t\t\t\tmyMap.balloon.open(coords, {\r\n\t\t\t\t\t\t\t\t\t\t\t\tcontentHeader:'Latfield-Lngfield Kordinatlar',\r\n\t\t\t\t\t\t\t\t\t\t\t\tcontentBody:'<p>Haritada Seçeceğiniz yerin üstüne tıklayıp, çıkan kordinatları aşağı kopyalayın</p>' +\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t'<p>Kordinatlar: ' + [\r\n\t\t\t\t\t\t\t\t\t\t\t\t\tcoords[0].toPrecision(6),\r\n\t\t\t\t\t\t\t\t\t\t\t\t\tcoords[1].toPrecision(6)\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t].join(', ') + '</p>',\r\n\t\t\t\t\t\t\t\t\t\t\t\tcontentFooter:'<sup>Kopyalayın</sup>'\r\n\t\t\t\t\t\t\t\t\t\t\t});\r\n\t\t\t\t\t\t\t\t\t\t\t\$('#latfield').val(coords[0].toPrecision(6));\r\n\t\t\t\t\t\t\t\t\t\t\t\$('#lngfield').val(coords[1].toPrecision(6));\r\n\t\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t\t\telse {\r\n\t\t\t\t\t\t\t\t\t\t\tmyMap.balloon.close();\r\n\t\t\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t\t\t});\r\n\t\t\t\t\t\t\t\t\tmyMap.events.add('boundschange', function(event) {\r\n\t\t\t\t\t\t\t\t\t  \$('#zoom').val(event.get('newZoom'));\r\n\t\t\t\t\t\t\t\t\t});\r\n\t\t\t\t\t\t\t\t\t/**\r\n\t\t\t\t\t\t\t\t\t * \r\n\t\t\t\t\t\t\t\t\t * Processing events that occur when the user\r\n\t\t\t\t\t\t\t\t\t * right-clicks anywhere on the map.\r\n\t\t\t\t\t\t\t\t\t * When such an event occurs, we display a popup hint\r\n\t\t\t\t\t\t\t\t\t * at the point of click.\r\n\t\t\t\t\t\t\t\t\t */\r\n\t\t\t\t\t\t\t\t\tmyMap.events.add('contextmenu', function (e) {\r\n\t\t\t\t\t\t\t\t\t\tmyMap.hint.open(e.get('coords'), 'Someone right-clicked');\r\n\t\t\t\t\t\t\t\t\t});\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t// Hiding the hint when opening the balloon.\r\n\t\t\t\t\t\t\t\t\tmyMap.events.add('balloonopen', function (e) {\r\n\t\t\t\t\t\t\t\t\t\tmyMap.hint.close();\r\n\t\t\t\t\t\t\t\t\t});\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\tmyMap.geoObjects.add(myPlacemark1);\r\n\t\t\t\t\t\t\t\t}\r\n\t\t\t\t\t\t\t</script>\r\n\t\t\t\t\t\t\t<div class=\"row\">\r\n\t\t\t\t\t\t\t<label>Haritada İlan Latfield-Lngfield Kodlarını Belirleyip Aşağıdaki Alana Kopyala</label>\r\n\t\t\t\t\t\t\t<div class=\"form-group col-sm-12\" style=\"margin-left: -10px;padding-right: 0px;\">\r\n\t\t\t\t\t\t\t<div id=\"map-container\" class=\"homepage-map margin-bottom-0\">\r\n\t\t\t\t\t\t\t<div id=\"map\"></div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\t\t\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<div class=\"form-group col-sm-4\">\r\n\t\t\t\t\t\t\t<label>Latfield (İLK KORDİNAT)</label>\r\n\t\t\t\t\t\t\t<input type=\"text\" id=\"latfield\" class=\"form-control\" value=\"";
echo $Sonuc["latfield"];
echo "\"  name=\"latfield\" />\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<div class=\"form-group col-sm-4\">\r\n\t\t\t\t\t\t\t<label>Lngfield (İKİNCİ KORDİNAT)</label>\r\n\t\t\t\t\t\t\t<input type=\"text\" id=\"lngfield\" class=\"form-control\" value=\"";
echo $Sonuc["lngfield"];
echo "\" name=\"lngfield\" />\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<div class=\"guncellemegizle form-group col-sm-4\">\r\n\t\t\t\t\t\t\t<label>Zoom (ÖRNEK: 10)</label>\r\n\t\t\t\t\t\t\t<input id=\"zoom\" name=\"zoom\" class=\"form-control\" type=\"text\" value=\"";
echo $Sonuc["zoom"];
echo "\" />\r\n\t\t\t\t\t\t\t</div>\t\r\n\r\n\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t";
if (isset($_GET["islem"]) == "duzenle") {
    echo "\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n\t\t\t\t\t\t\t\t\t\t";
    if ($Sonuc["kapak"]) {
        echo "\t\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-2\">\r\n\t\t\t\t\t\t\t\t\t\t\t<img src=\"../";
        echo tema;
        echo "/uploads/emlaklar/";
        echo $Sonuc["kapak"];
        echo "\" class=\"img-responsive img-thumbnail\" style=\"margin-bottom:2px;width:100%;min-height:150px;max-height:250px;\">\r\n\t\t\t\t\t\t\t\t\t\t\t<a style=\"width: 100%;\" class=\"btn btn-danger btn-sm popconfirm\" title=\"Kapak Sil\" href=\"../_class/yonetim_islem.php?emlakresimsil=ok&sid=";
        echo $Sonuc["id"];
        echo "\"><i class=\"fas fa-trash\"></i> Kapak Sil</a>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t";
    }
    echo "\t\t\t\t\t\t\t\t\t\t";
    $resimler = $db->prepare("SELECT * FROM emlakresim WHERE pid = ? order by sira asc");
    $resimler->execute([$Sonuc["id"]]);
    $ral = $resimler->fetchALL(PDO::FETCH_ASSOC);
    echo "\t\t\t\t\t\t\t\t\t\t";
    foreach ($ral as $r) {
        $sira = $r["sira"];
        echo "\t\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-2\">\r\n\t\t\t\t\t\t\t\t\t\t\t<img src=\"../";
        echo tema;
        echo "/uploads/emlaklar/diger/";
        echo $r["resim"];
        echo "\" class=\"img-responsive img-thumbnail\" style=\"margin-bottom:2px;width:100%;min-height:150px;max-height:250px;\">\r\n\t\t\t\t\t\t\t\t\t\t\t<label>Gösterim Sırası</label>\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"number\" value=\"";
        echo $sira;
        echo "\" class=\"form-control\" min=\"0\" onchange=\"emlakResimSirala('";
        echo $r["id"];
        echo "',this.value)\"> \r\n\t\t\t\t\t\t\t\t\t\t\t<a style=\"width: 100%;\" class=\"btn btn-danger btn-sm popconfirm\" title=\"Resmi Sil\" href=\"../_class/yonetim_islem.php?emlaktopluresimsil=ok&id=";
        echo $Sonuc["id"];
        echo "&sid=";
        echo $r["id"];
        echo "\"><i class=\"fas fa-trash\"></i> Resmi Sil</a>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t";
    }
    echo "\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t";
}
echo "\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group row col-md-6\">\r\n\t\t\t\t\t\t\t\t\t<label>Listeleme Görseli</label>\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"file\" name=\"resim\" class=\"file-upload-default\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"input-group col-xs-12\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control file-upload-info form-control-sm\" disabled=\"\" placeholder=\"Resim dosyası seçiniz\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-append\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"file-upload-browse btn btn-primary btn-sm\" type=\"button\"><i class=\"icon-cloud-upload font-12\"></i> Dosya Seç</button>\r\n\t\t\t\t\t\t\t\t\t\t\t</span>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group row col-md-6\">\r\n\t\t\t\t\t\t\t\t\t<label>Fotoğraflar</label>\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"file\" name=\"resimler[]\" multiple class=\"file-upload-default\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"input-group col-xs-12\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control file-upload-info form-control-sm\" disabled=\"\" placeholder=\"Ürüne ait resimleri toplu şekilde buradan seçebilirsiniz.\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-append\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"file-upload-browse btn btn-primary btn-sm\" type=\"button\"><i class=\"icon-cloud-upload font-12\"></i> Dosya Seç</button>\r\n\t\t\t\t\t\t\t\t\t\t\t</span>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t";
if (isset($_GET["islem"]) == "duzenle") {
    echo "\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t";
    if ($Sonuc["katalog"]) {
        echo "\t\t\t\t\t\t\t\t\t\t<div class=\"form-group col-md-3\">\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"btn btn-primary btn-sm mr-2\" target=\"_blank\" href=\"../";
        echo tema;
        echo "/uploads/emlaklar/katalog/";
        echo $Sonuc["katalog"];
        echo "\"><i class=\"fa fa-download\" aria-hidden=\"true\"></i></a>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"btn btn-danger btn-sm popconfirm\" title=\"Katalog Sil\" href=\"../_class/yonetim_islem.php?katalogsil=ok&sid=";
        echo $Sonuc["id"];
        echo "\"><i class=\"fas fa-trash\"></i> E-Katalog Sil</a>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t";
    }
    echo "\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t";
}
echo "\t\t\t\t\t\t\t\t\t<div class=\"form-group row col-md-6\">\r\n\t\t\t\t\t\t\t\t\t<label>E-Katalog</label>\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"file\" name=\"katalog\" class=\"file-upload-default\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"input-group col-xs-12\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control file-upload-info form-control-sm\" disabled=\"\" placeholder=\"E-Katalog dosyası seçiniz\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-append\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"file-upload-browse btn btn-primary btn-sm\" type=\"button\"><i class=\"icon-cloud-upload font-12\"></i> Dosya Seç</button>\r\n\t\t\t\t\t\t\t\t\t\t\t</span>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-2\">\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t";
if (isset($_GET["islem"]) == "duzenle") {
    echo "\t\t\t\t\t\t\t\t\t\t<label class=\"switch\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"durum\" id=\"durum\" value=\"1\" ";
    if ($Sonuc["durum"] == "1") {
        echo " checked ";
    }
    echo ">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t";
} else {
    echo "\t\t\t\t\t\t\t\t\t\t<label class=\"switch\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"durum\" id=\"durum\" value=\"1\" checked>\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t";
}
echo "\t\t\t\t\t\t\t\t\t\t<label class=\"d-inline-block\" style=\"line-height: 34px;\" for=\"durum\">Durum</label>\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-2\">\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t";
if (isset($_GET["islem"]) == "duzenle") {
    echo "\t\t\t\t\t\t\t\t\t\t<label class=\"switch\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"anasayfa\" id=\"anasayfa\" value=\"1\" ";
    if ($Sonuc["anasayfa"] == "1") {
        echo " checked ";
    }
    echo ">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t";
} else {
    echo "\t\t\t\t\t\t\t\t\t\t<label class=\"switch\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"anasayfa\" id=\"anasayfa\" value=\"1\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t";
}
echo "\t\r\n\t\t\t\t\t\t\t\t\t\t<label class=\"d-inline-block\" style=\"line-height: 34px;\" for=\"anasayfa\">Vitrin'de Gözüksün mü ?</label>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"aciklama\">İçerik</label>\r\n\t\t\t\t\t\t\t\t\t\t<textarea name=\"aciklama\" id=\"myTextarea\">";
echo isset($_GET["islem"]) == "duzenle" ? $Sonuc["aciklama"] : "";
echo "</textarea>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"tab-pane fade\" id=\"emlak-ozellikleri\" role=\"tabpanel\" aria-labelledby=\"contact-tab-vertical\">\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"tab-pane\" id=\"ozellikler\">\r\n\t\t\t\t\t\t\t\t\t\t<div id=\"secyaz\"></div>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"tab-pane fade\" id=\"seo-ayarlari\" role=\"tabpanel\" aria-labelledby=\"contact-tab-vertical\">\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"maxlength-textarea\">SEO Açıklama (Description)</label>\r\n\t\t\t\t\t\t\t\t\t\t<textarea id=\"maxlength-textarea\" name=\"description\"  class=\"form-control\" maxlength=\"260\" rows=\"2\">";
echo isset($_GET["islem"]) == "duzenle" ? $Sonuc["description"] : "";
echo "</textarea>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n\t\t\t\t\t\t\t\t\t\t<label for=\"tags\">SEO Kelimeler (Keywords) <small>(Kelimenin sonuna virgül koyunuz)</small></label>\r\n\t\t\t\t\t\t\t\t\t\t<input name=\"keywords\" id=\"tags\" value=\"";
echo isset($_GET["islem"]) == "duzenle" ? $Sonuc["keywords"] : "";
echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-3\"></div>\r\n\t\t\t\t\t\t<div class=\"col-9\">\r\n\t\t\t\t\t\t\t";
if (isset($_GET["islem"]) == "duzenle") {
    echo "\t\t\t\t\t\t\t<button type=\"submit\" name=\"emlak_guncelle\" class=\"btn btn-success btn-icon-text btn-sm mt-3\">\r\n\t\t\t\t\t\t\t\t<i class=\"mdi mdi-reload  btn-icon-prepend\"></i>                                                    \r\n\t\t\t\t\t\t\t\tGÜNCELLE\r\n\t\t\t\t\t\t\t</button>\r\n\t\t\t\t\t\t\t";
} else {
    echo "\t\t\t\t\t\t\t<button type=\"submit\" name=\"emlak_ekle\" class=\"btn btn-primary btn-icon-text btn-sm mt-3\">\r\n\t\t\t\t\t\t\t\t<i class=\"mdi mdi-file-check btn-icon-prepend\"></i>\r\n\t\t\t\t\t\t\t\tKAYDET\r\n\t\t\t\t\t\t\t</button>\r\n\t\t\t\t\t\t\t";
}
echo "\t\t\t\t\t\t</div>\t\t\t\t\t\t\r\n\t\t\t\t\t</div>\t\t\t\t\t\t\r\n\r\n\t\t\t\t</form>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</div>\r\n\r\n</div>\r\n\r\n\r\n<script type=\"text/javascript\">\r\n\$(document).ready(function(e) {\r\n\t\$('#secenek').bind('change', secenekGetir);\r\n});\r\nfunction secenekGetir()\r\n{\r\n\tvar id\t\t=\$(this).val();\t\r\n\tvar ozellik\t=\$(\"#ozellik\").val();\r\n\tvar dil\t\t=\$(\"#dil\").val();\r\n\t\$.ajax({\r\n\t\ttype: 'post',\r\n\t\turl: 'data/secenek.php',\r\n\t\tdata:{\"id\":id,\"ozellik\":ozellik,\"dil\":dil},\r\n\t\tsuccess: function(result) \r\n\t\t{\r\n\t\t\t\$('#secyaz').html(result);\r\n\t\t}\r\n\t});\r\n}\r\n\r\n\$('#secenek').ready(function(){\r\n\tvar id \t\t= \$(\"#secenek\").val();\r\n\tvar ozellik\t= \$(\"#ozellik\").val();\r\n\tvar dil\t\t= \$(\"#dil\").val();\r\n\tif(id != 0)\r\n\t{\r\n\t \$.ajax({\r\n\t\ttype: 'post',\r\n\t\turl: 'data/secenek.php',\r\n\t\tdata:{\"id\":id,\"ozellik\":ozellik,\"dil\":dil},\r\n\t\tsuccess: function(result) \r\n\t\t{\r\n\t\t\t\$('#secyaz').html(result);\r\n\t\t}\r\n\t\t});\r\n\t}\r\n\telse\r\n\t{\r\n\t\t\$(\"#secyaz\").html('Kategori Seçiniz.');\r\n\t}\r\n});\t\r\n</script>\r\n<script>\r\n\t\$(document).ready(function(e) {\r\n\t\t\$('#il').bind('change', ilceleriGetir);\r\n\t\t\$('#ilce').bind('change', semtleriGetir);\r\n\t});\r\n\r\n\tfunction ilceleriGetir() {\r\n\t\tvar ilid = \$(this).val();\r\n\t\tvar ilceid=\$(\"#ilceid\").val();\r\n\t\t\$.ajax({\r\n\t\t\ttype: \"post\",\r\n\t\t\turl: \"dinamik.php\",\r\n\t\t\tdata: {\r\n\t\t\t\t\"ilid\": ilid,\r\n\t\t\t\t\"ilceid\": ilceid\r\n\t\t\t},\r\n\t\t\tdataType: \"json\",\r\n\t\t\tsuccess: function(fur) {\r\n\t\t\t\t\$(\"#ilce\").html(fur.basari);\r\n\t\t\t}\r\n\t\t});\r\n\t}\r\n\tfunction emlakResimSirala(resimID,sira){\r\n\t    \r\n\t    \$.ajax({\r\n\t\t\ttype: \"post\",\r\n\t\t\turl: \"/";
echo tema;
echo "/ajax/ajax.php\",\r\n\t\t\tdata: {\r\n\t\t\t\t\"resim_id\": resimID,\r\n\t\t\t\t\"sira\": sira,\r\n\t\t\t\t'type':'emlakResimSirala'\r\n\t\t\t},\r\n\t\t\tdataType: \"POST\"\r\n\t\t});\r\n\t\t\r\n\t\t\$.toast({\r\n\t\t  heading: 'Başarılı!',\r\n\t\t  text: 'Başarı ile guncellenmiştir.',\r\n\t\t  showHideTransition: 'slide',\r\n\t\t  icon: 'success',\r\n\t\t  loaderBg: '#fff',\r\n\t\t  position: 'top-right'\r\n\t\t});\r\n\t}\r\n\r\n\tfunction semtleriGetir() {\r\n\t\tvar ilceid = \$(\"#ilce\").val();\r\n\t\tvar semtid = \$(\"#semtid\").val();\r\n\t\t\$.ajax({\r\n\t\t\ttype: \"post\",\r\n\t\t\turl: \"dinamik.php\",\r\n\t\t\tdata: {\r\n\t\t\t\t\"ilceid\": ilceid,\r\n\t\t\t\t\"semtid\": semtid\r\n\t\t\t},\r\n\t\t\tdataType: \"json\",\r\n\t\t\tsuccess: function(fur) {\r\n\t\t\t\t\$(\"#semt\").html(fur.basari);\r\n\t\t\t}\r\n\t\t});\r\n\t}\r\n\r\n\t\$('#il').ready(function() {\r\n\t\tvar ilid = \$(\"#il\").val();\r\n\t\tvar ilceid=\$(\"#ilceid\").val();\r\n\t\tvar semtid=\$(\"#semtid\").val();\r\n\t\tif (ilid != 0) {\r\n\t\t\t\$.ajax({\r\n\t\t\t\ttype: \"post\",\r\n\t\t\t\turl: \"dinamik.php\",\r\n\t\t\t\tdata: {\r\n\t\t\t\t\t\"ilid\": ilid,\r\n\t\t\t\t\t\"ilceid\": ilceid,\r\n\t\t\t\t\t\"semtid\": semtid\r\n\t\t\t\t},\r\n\t\t\t\tdataType: \"json\",\r\n\t\t\t\tsuccess: function(fur) {\r\n\t\t\t\t\t\$(\"#ilce\").html(fur.basari);\r\n\t\t\t\t\tsetTimeout(function() { semtleriGetir(); }, 500);\r\n\t\t\t\t}\r\n\t\t\t});\r\n\t\t} else {\r\n\t\t\t\$(\"#ilce\").html('<option value=\"0\">İlçe Seçiniz</option>');\r\n\t\t}\r\n\t});\r\n</script>\r\n";
mesaj("emlak_ekle", 2, "no", "Hata oluştu tekrar deneyiniz.!");
mesaj("emlak_guncelle", 1, "yes", "Başarı ile guncellenmiştir.");
mesaj("emlak_guncelle", 2, "no", "Hata oluştu tekrar deneyiniz.!");
mesaj("emlakresimsil", 1, "yes", "Başarı ile siinmiştir.");
mesaj("emlakresimsil", 2, "no", "Hata oluştu tekrar deneyiniz.!");
mesaj("emlaktopluresimsil", 1, "yes", "Başarı ile siinmiştir.");
mesaj("emlaktopluresimsil", 2, "no", "Hata oluştu tekrar deneyiniz.!");
mesaj("dokumansil", 1, "yes", "Başarı ile siinmiştir.");
mesaj("dokumansil", 2, "no", "Hata oluştu tekrar deneyiniz.!");
mesaj("katalogsil", 1, "yes", "Başarı ile siinmiştir.");
mesaj("katalogsil", 2, "no", "Hata oluştu tekrar deneyiniz.!");


?>