<?php


echo !defined("GUVENLIK") ? exit : NULL;
oturumkontrol($url);
$ayar_dizi = $db->prepare("SELECT * FROM moduller WHERE id = ?");
$ayar_dizi->execute([1]);
if ($ayar_dizi->rowCount()) {
    $Sonuc = $ayar_dizi->fetch(PDO::FETCH_ASSOC);
    echo "<div class=\"page-header\">\r\n\t<div class=\"page-title mt-0 mb-0\">\r\n\t\t<h3>";
    echo $admindil["txt7"];
    echo "</h3>\r\n\t\t<div class=\"crumbs\">\r\n\t\t\t<ul id=\"breadcrumbs\" class=\"breadcrumb\">\r\n\t\t\t\t<li><a href=\"./\"><i class=\"icon-home menu-icon\"></i></a></li>\r\n\t\t\t\t<li><a href=\"";
    echo $sayfalink;
    echo "\">";
    echo $admindil["txt2"];
    echo "</a></li>\r\n\t\t\t\t<li class=\"active\"><a href=\"";
    echo $sayfalink;
    echo "\">";
    echo $admindil["txt7"];
    echo "</a></li>\r\n\t\t\t</ul>\r\n\t\t</div>\r\n\t</div>\r\n</div>\r\n<div class=\"row\">\r\n\t<div class=\"col-12 grid-margin stretch-card\">\r\n\t\t<div class=\"card\">\r\n\t\t\t<div class=\"card-body\">\r\n\t\t\t<form class=\"forms-sample\" method=\"post\" action=\"../_class/uptade.php\" enctype=\"multipart/form-data\">\r\n\t\t\t\t<input id=\"id\" name=\"id\" type=\"hidden\" value=\"";
    echo $Sonuc["id"];
    echo "\">\r\n\t\t\t\t<div class=\"row\">\r\n\t\t\t\t\t<div class=\"col-md-6\">\r\n\t\t\t\t\t\t<h6 class=\"card-title\">Anasayfa Modülleri</h6>\r\n\t\t\t\t\t\t<div id=\"dragula-event-left\" class=\"py-2\">\r\n\t\t\t\t\t\t\t<div class=\"card rounded border mb-2\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"media row\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-9 col-md-9 col-sm-6\">\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi float-left mt-2 mdi-check icon-sm text-primary align-self-center mr-3\"></i>\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"mb-1\">Slider Üzeri Bilgi</h6>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"mb-0 text-muted\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\tAnasayfadaki slider üzerindeki bilgi alanını kapatıp açabilirsiniz.\r\n\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 text-right\">\r\n\t\t\t\t\t\t\t\t\t\t<label class=\"switch mb-0\" style=\"margin-top: 1px;\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"alan1\" id=\"alan1\" ";
    if ($Sonuc["alan1"] == "1") {
        echo " checked ";
    }
    echo " value=\"1\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<div class=\"card rounded border mb-2\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"media row\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-9 col-md-9 col-sm-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi float-left mt-2 mdi-check icon-sm text-primary align-self-center mr-3\"></i>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"mb-1\">Slider Üzeri Arama Alanı</h6>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"mb-0 text-muted\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\tAnasayfadaki slider üzerindeki arama alanını kapatıp açabilirsiniz.\r\n\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 text-right\">\r\n\t\t\t\t\t\t\t\t\t\t<label class=\"switch mb-0\" style=\"margin-top: 1px;\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"alan2\" id=\"alan2\" ";
    if ($Sonuc["alan2"] == "1") {
        echo " checked ";
    }
    echo " value=\"1\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<div class=\"card rounded border mb-2\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"media row\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-9 col-md-9 col-sm-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi float-left mt-2 mdi-check icon-sm text-primary align-self-center mr-3\"></i>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"mb-1\">Anasayfa Vitin İlanları</h6>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"mb-0 text-muted\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\tAnasayfadaki vitrin alanını kapatıp açabilirsiniz.\r\n\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 text-right\">\r\n\t\t\t\t\t\t\t\t\t\t<label class=\"switch mb-0\" style=\"margin-top: 1px;\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"alan3\" id=\"alan3\" ";
    if ($Sonuc["alan3"] == "1") {
        echo " checked ";
    }
    echo " value=\"1\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<div class=\"card rounded border mb-2\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"media row\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-9 col-md-9 col-sm-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi float-left mt-2 mdi-check icon-sm text-primary align-self-center mr-3\"></i>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"mb-1\">Anasayfa İlan Kategori Listeme 1 Alanı</h6>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"mb-0 text-muted\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\tAnasayfadaki bir kategoriye ait ilan listesi alanını kapatıp açabilirsiniz.\r\n\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 text-right\">\r\n\t\t\t\t\t\t\t\t\t\t<label class=\"switch mb-0\" style=\"margin-top: 1px;\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"alan4\" id=\"alan4\" ";
    if ($Sonuc["alan4"] == "1") {
        echo " checked ";
    }
    echo " value=\"1\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<div class=\"card rounded border mb-2\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"media row\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-9 col-md-9 col-sm-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi float-left mt-2 mdi-check icon-sm text-primary align-self-center mr-3\"></i>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"mb-1\">Anasayfa İlan Kategori Listeme 2 Alanı</h6>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"mb-0 text-muted\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\tAnasayfadaki bir kategoriye ait ilan listesi alanını kapatıp açabilirsiniz.\r\n\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 text-right\">\r\n\t\t\t\t\t\t\t\t\t\t<label class=\"switch mb-0\" style=\"margin-top: 1px;\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"alan5\" id=\"alan5\" ";
    if ($Sonuc["alan5"] == "1") {
        echo " checked ";
    }
    echo " value=\"1\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<div class=\"card rounded border mb-2\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"media row\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-9 col-md-9 col-sm-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi float-left mt-2 mdi-check icon-sm text-primary align-self-center mr-3\"></i>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"mb-1\">Anasayfa Danışmanlarımız Alanı</h6>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"mb-0 text-muted\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\tAnasayfadaki danışmanlarmız alanını kapatıp açabilrsiniz.\r\n\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 text-right\">\r\n\t\t\t\t\t\t\t\t\t\t<label class=\"switch mb-0\" style=\"margin-top: 1px;\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"alan6\" id=\"alan6\" ";
    if ($Sonuc["alan6"] == "1") {
        echo " checked ";
    }
    echo " value=\"1\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t<div class=\"card rounded border mb-2\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"media row\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-9 col-md-9 col-sm-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi float-left mt-2 mdi-check icon-sm text-primary align-self-center mr-3\"></i>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"mb-1\">Anasayfa Müşteri Görüşleri Alanı</h6>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"mb-0 text-muted\">\r\n\t\t\t\t\t\t\t\t\t\t\t\tAnasayfadaki müşteri görüşleri alanını kapatıp açabilrsiniz.\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 text-right\">\r\n\t\t\t\t\t\t\t\t\t\t<label class=\"switch mb-0\" style=\"margin-top: 1px;\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"alan7\" id=\"alan7\" ";
    if ($Sonuc["alan7"] == "1") {
        echo " checked ";
    }
    echo " value=\"1\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t<div class=\"card rounded border mb-2\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"media row\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-9 col-md-9 col-sm-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi float-left mt-2 mdi-check icon-sm text-primary align-self-center mr-3\"></i>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"mb-1\">Anasayfa Son Projelerimiz Alanı</h6>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"mb-0 text-muted\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\tAnasayfadaki son projelerimiz alanını kapatıp açabilirsiniz.\r\n\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 text-right\">\r\n\t\t\t\t\t\t\t\t\t\t<label class=\"switch mb-0\" style=\"margin-top: 1px;\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"alan8\" id=\"alan8\" ";
    if ($Sonuc["alan8"] == "1") {
        echo " checked ";
    }
    echo " value=\"1\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t<div class=\"card rounded border mb-2\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"media row\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-9 col-md-9 col-sm-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi float-left mt-2 mdi-check icon-sm text-primary align-self-center mr-3\"></i>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"mb-1\">Anasayfa Referanslar Alanı</h6>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"mb-0 text-muted\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\tAnasayfadaki referanslar alanını kapatıp açabilrsiniz.\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 text-right\">\r\n\t\t\t\t\t\t\t\t\t\t<label class=\"switch mb-0\" style=\"margin-top: 1px;\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"alan9\" id=\"alan9\" ";
    if ($Sonuc["alan9"] == "1") {
        echo " checked ";
    }
    echo " value=\"1\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t<div class=\"card rounded border mb-2\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"media row\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-9 col-md-9 col-sm-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi float-left mt-2 mdi-check icon-sm text-primary align-self-center mr-3\"></i>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"mb-1\">Anasayfa Paketlerimiz Alanı</h6>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"mb-0 text-muted\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\tAnasayfadaki paketlerimiz alanını kapatıp açabilirsiniz.\r\n\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 text-right\">\r\n\t\t\t\t\t\t\t\t\t\t<label class=\"switch mb-0\" style=\"margin-top: 1px;\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"alan10\" id=\"alan10\" ";
    if ($Sonuc["alan10"] == "1") {
        echo " checked ";
    }
    echo " value=\"1\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<div class=\"card rounded border mb-2\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"media row\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-9 col-md-9 col-sm-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi float-left mt-2 mdi-check icon-sm text-primary align-self-center mr-3\"></i>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"mb-1\">Anasayfa Haberler ve Duyurular Alanı</h6>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"mb-0 text-muted\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\tAnasayfadaki haberler ve duyurular alanını kapatıp açabilirsiniz.\r\n\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 text-right\">\r\n\t\t\t\t\t\t\t\t\t\t<label class=\"switch mb-0\" style=\"margin-top: 1px;\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"alan11\" id=\"alan11\" ";
    if ($Sonuc["alan11"] == "1") {
        echo " checked ";
    }
    echo " value=\"1\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<div class=\"card rounded border mb-2\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"media row\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-9 col-md-9 col-sm-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi float-left mt-2 mdi-check icon-sm text-primary align-self-center mr-3\"></i>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"mb-1\">Anasayfa Hakkımızda Alanı</h6>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"mb-0 text-muted\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\tAnasayfadaki hakkımızda alanını kapatıp açabilirsiniz.\r\n\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 text-right\">\r\n\t\t\t\t\t\t\t\t\t\t<label class=\"switch mb-0\" style=\"margin-top: 1px;\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"alan12\" id=\"alan12\" ";
    if ($Sonuc["alan12"] == "1") {
        echo " checked ";
    }
    echo " value=\"1\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\r\n\t\t\t\t\t<div class=\"col-md-6\">\r\n\t\t\t\t\t\t<h6 class=\"card-title\">Diğer Modüller</h6>\r\n\t\t\t\t\t\t<div id=\"dragula-event-right\" class=\"py-2\">\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<div class=\"card rounded border mb-2\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"media row\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-9 col-md-9 col-sm-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi float-left mt-2 mdi-check icon-sm text-primary align-self-center mr-3\"></i>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"mb-1\">Üyelik</h6>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"mb-0 text-muted\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\tSitedeki üyelik modülünü kapatıp açabilirsiniz.\r\n\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 text-right\">\r\n\t\t\t\t\t\t\t\t\t\t<label class=\"switch mb-0\" style=\"margin-top: 1px;\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"alan13\" id=\"alan13\" ";
    if ($Sonuc["alan13"] == "1") {
        echo " checked ";
    }
    echo " value=\"1\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<div class=\"card rounded border mb-2\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"media row\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-9 col-md-9 col-sm-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi float-left mt-2 mdi-check icon-sm text-primary align-self-center mr-3\"></i>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"mb-1\">Danışmana Mesaj Gönder</h6>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"mb-0 text-muted\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\tSitedeki danışmana gönder modülünü kapatıp açabilirsiniz.\r\n\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 text-right\">\r\n\t\t\t\t\t\t\t\t\t\t<label class=\"switch mb-0\" style=\"margin-top: 1px;\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"alan14\" id=\"alan14\" ";
    if ($Sonuc["alan14"] == "1") {
        echo " checked ";
    }
    echo " value=\"1\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<!--\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<div class=\"card rounded border mb-2\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"media row\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-9 col-md-9 col-sm-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi float-left mt-2 mdi-check icon-sm text-primary align-self-center mr-3\"></i>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"mb-1\">Yükleniyor</h6>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"mb-0 text-muted\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\tSitedeki sayfa yükleniyor alanını kapatıp açabilirsiniz.\r\n\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 text-right\">\r\n\t\t\t\t\t\t\t\t\t\t<label class=\"switch mb-0\" style=\"margin-top: 1px;\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"alan15\" id=\"alan15\" ";
    if ($Sonuc["alan15"] == "1") {
        echo " checked ";
    }
    echo " value=\"1\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t--->\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<div class=\"card rounded border mb-2\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"media row\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-9 col-md-9 col-sm-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi float-left mt-2 mdi-check icon-sm text-primary align-self-center mr-3\"></i>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"mb-1\">.html uzantı</h6>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"mb-0 text-muted\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\tSitenizin .html uzantılı açılmasını kapatıp açabilirsiniz.\r\n\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 text-right\">\r\n\t\t\t\t\t\t\t\t\t\t<label class=\"switch mb-0\" style=\"margin-top: 1px;\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"alan16\" id=\"alan16\" ";
    if ($Sonuc["alan16"] == "1") {
        echo " checked ";
    }
    echo " value=\"1\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<div class=\"card rounded border mb-2\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"media row\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-9 col-md-9 col-sm-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi float-left mt-2 mdi-check icon-sm text-primary align-self-center mr-3\"></i>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"mb-1\">SSL</h6>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"mb-0 text-muted\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\tSitenizin ssl'li şekilde açılmasını kapatıp açabilirsiniz.\r\n\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 text-right\">\r\n\t\t\t\t\t\t\t\t\t\t<label class=\"switch mb-0\" style=\"margin-top: 1px;\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"alan17\" id=\"alan17\" ";
    if ($Sonuc["alan17"] == "1") {
        echo " checked ";
    }
    echo " value=\"1\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<div class=\"card rounded border mb-2\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"media row\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-9 col-md-9 col-sm-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi float-left mt-2 mdi-check icon-sm text-primary align-self-center mr-3\"></i>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"mb-1\">Alt Klasörde Çalışsınmı ?</h6>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"mb-0 text-muted\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\tSitenizi alt klasörde kurulu değilse bu seçeneği açmayınız.\r\n\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 text-right\">\r\n\t\t\t\t\t\t\t\t\t\t<label class=\"switch mb-0\" style=\"margin-top: 1px;\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"alan18\" id=\"alan18\" ";
    if ($Sonuc["alan18"] == "1") {
        echo " checked ";
    }
    echo " value=\"1\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t<div class=\"card rounded border mb-2\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"media row\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-9 col-md-9 col-sm-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi float-left mt-2 mdi-check icon-sm text-primary align-self-center mr-3\"></i>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"mb-1\">Site Bakım Modu</h6>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"mb-0 text-muted\">Sitenizi bakım moduna alır.</p>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<b style=\"color:red; font-size: 11px;\" >Site bakım modunu eğer yönetim paneline giriş yapmışsanız göremezsiniz.(Bu şekilde yönetim panelinde yapmış olduğunuz değişiklikleri bakım modunu kapatmadan görebileceksiniz.!)</b>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 text-right\">\r\n\t\t\t\t\t\t\t\t\t\t<label class=\"switch mb-0\" style=\"margin-top: 1px;\">\r\n\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"alan19\" id=\"alan19\" ";
    if ($Sonuc["alan19"] == "1") {
        echo " checked ";
    }
    echo " value=\"1\">\r\n\t\t\t\t\t\t\t\t\t\t\t<span class=\"slider\"></span>\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t</div>\t\r\n\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t<div class=\"card rounded border mb-2\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"media row\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-9 col-md-9 col-sm-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi float-left mt-2 mdi-check icon-sm text-primary align-self-center mr-3\"></i>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"mb-1\">Anasayfa'da kategori alanı 1</h6>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"mb-0 text-muted\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\tLütfen ilgili kısımda hangi kategori içerikleri çıkacaksa onu seçiniz.\r\n\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 text-right\">\r\n\t\t\t\t\t\t\t\t\t\t<label style=\"margin-top: 1px;\">\r\n\t\t\t\t\t\t\t\t\t\t\t<select name=\"alan20\" class=\"form-control\"> \r\n\t\t\t\t\t\t\t\t\t\t\t<optgroup label=\"Emlak Kategori\">\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t";
    modulmenukategori(0, 0, $Sonuc["alan20"], $Sonuc["alan20"]);
    echo "\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t</optgroup>\r\n\t\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t</div>\t\r\n\r\n\t\t\t\t\t\t\t\t<div class=\"card rounded border mb-2\">\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t<div class=\"media row\">\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-9 col-md-9 col-sm-6\">\r\n\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi float-left mt-2 mdi-check icon-sm text-primary align-self-center mr-3\"></i>\r\n\t\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t<h6 class=\"mb-1\">Anasayfa'da kategori alanı 2</h6>\r\n\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"mb-0 text-muted\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\tLütfen ilgili kısımda hangi kategori içerikleri çıkacaksa onu seçiniz.\r\n\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n\t\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 text-right\">\r\n\t\t\t\t\t\t\t\t\t\t<label style=\"margin-top: 1px;\">\r\n\t\t\t\t\t\t\t\t\t\t\t<select name=\"alan21\" class=\"form-control\"> \r\n\t\t\t\t\t\t\t\t\t\t\t<optgroup label=\"Emlak Kategori\">\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t";
    modulmenukategori(0, 0, $Sonuc["alan21"], $Sonuc["alan21"]);
    echo "\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t</optgroup>\r\n\t\t\t\t\t\t\t\t\t\t\t</select>\r\n\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t</label>\r\n\t\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t</div>\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t</div>\t\t\t\t\t\t\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div class=\"col-md-12\">\r\n\t\t\t\t\t<input type=\"hidden\" name=\"url\" value=\"";
    echo $_SERVER["REQUEST_URI"];
    echo "\" />\r\n\t\t\t\t\t<button type=\"submit\" name=\"modul_guncelle\" class=\"btn btn-success btn-icon-text btn-sm\">\r\n\t\t\t\t\t\t<i class=\"mdi mdi-spin mdi-loading\"></i>                                                   \r\n\t\t\t\t\t\tGÜNCELLE\r\n\t\t\t\t\t</button>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\t\t\t\t</form>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</div>\r\n</div>\r\n";
    mesaj("modul_guncelle", 1, "yes", "Başarı ile guncellenmiştir.");
    mesaj("modul_guncelle", 2, "no", "Hata oluştu tekrar deneyiniz.!");
    
} else {
    header("Location:" . $url . "/404" . $html . "");
    exit;
}

?>