<?php


echo !defined("GUVENLIK") ? exit : NULL;
oturumkontrol($url);
$ayar_dizi = $db->prepare("SELECT * FROM sabit_url");
$ayar_dizi->execute([]);
if ($ayar_dizi->rowCount()) {
    $Sonuc = $ayar_dizi->fetch(PDO::FETCH_ASSOC);
    echo "<div class=\"page-header\">\r\n\t<div class=\"page-title mt-0 mb-0\">\r\n\t\t<h3>";
    echo $admindil["txt25"];
    echo "</h3>\r\n\t\t<div class=\"crumbs\">\r\n\t\t\t<ul id=\"breadcrumbs\" class=\"breadcrumb\">\r\n\t\t\t\t<li><a href=\"./\"><i class=\"icon-home menu-icon\"></i></a></li>\r\n\t\t\t\t<li><a href=\"";
    echo $sayfalink;
    echo "\">";
    echo $admindil["txt17"];
    echo "</a></li>\r\n\t\t\t\t<li class=\"active\"><a href=\"";
    echo $sayfalink;
    echo "\">";
    echo $admindil["txt25"];
    echo "</a></li>\r\n\t\t\t</ul>\r\n\t\t</div>\r\n\t</div>\r\n</div>\r\n<div class=\"row\">\r\n\t<div class=\"col-12 grid-margin stretch-card\">\r\n\t\t<div class=\"card\">\r\n\t\t\t<div class=\"card-body\">\r\n\t\t\t\t<form class=\"forms-sample\" method=\"post\" action=\"../_class/yonetim_islem.php\" enctype=\"multipart/form-data\">\r\n\t\t\t\t\t\t<input type=\"hidden\" name=\"durum\" id=\"durum\" value=\"1\" />\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"alert alert-danger\" role=\"alert\">\r\n\t\t\t\t\t\t\t<i class=\"mdi mdi-alert-circle\" style=\"font-size: 50px;line-height: normal;float: left;\"></i>\r\n\t\t\t\t\t\t\t<p>AŞAĞIDA YAPACAĞINIZ HER DEĞİŞİKLİK İÇİN DEĞİŞİLİK YAPTIĞINIZ ALANLA İLGİLİ <b>MENÜ YÖNETİMİ</b> -> <b>HEDAER MENÜ</b> -> <b>FOOTER MENÜ</b>'de DEĞİŞİKLİK YAPMAYI UNUTMAYINIZ.!</p>\r\n\t\t\t\t\t\t\t<p>İŞLEMLERİN EN SONUNDA WEB SİTENİZDE ANASAYFA'YA GELEREK SAYFAYI YENİLEDİKTEN SONRA KONTROL EDİNİZ.!</p>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t<div class=\"row\">\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">Anasayfa</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"anaurl\"  value=\"";
    echo $Sonuc["anaurl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">Emlak Kategoriler</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"emlakkategoriurl\"  value=\"";
    echo $Sonuc["emlakkategoriurl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">İlanlar</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"ilanlarurl\"  value=\"";
    echo $Sonuc["ilanlarurl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">İlan Detayı</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"ilandetayurl\"  value=\"";
    echo $Sonuc["ilandetayurl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">Proje Kategoriler</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"projekategoriurl\"  value=\"";
    echo $Sonuc["projekategoriurl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">Projeler</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"projelerurl\"  value=\"";
    echo $Sonuc["projelerurl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">Proje Detayı</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"projedetayurl\"  value=\"";
    echo $Sonuc["projedetayurl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">Referanslar</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"refurl\" value=\"";
    echo $Sonuc["refurl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">Referans Detayı</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"refdetayurl\" value=\"";
    echo $Sonuc["refdetayurl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">Müşteri Görüşleri</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"musteriurl\" value=\"";
    echo $Sonuc["musteriurl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">Belgelerimiz</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"belgeurl\" value=\"";
    echo $Sonuc["belgeurl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\t\t\t\t\t\r\n\t\t\t\t\t\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">İletişim</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"iletisimurl\" value=\"";
    echo $Sonuc["iletisimurl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">Ekibimiz</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"ekiburl\" value=\"";
    echo $Sonuc["ekiburl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">Ekip Detayı</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"ekibdetayurl\" value=\"";
    echo $Sonuc["ekibdetayurl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">E-Katalog</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"katalogurl\" value=\"";
    echo $Sonuc["katalogurl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">Hizmetlerimiz</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"hizmeturl\" value=\"";
    echo $Sonuc["hizmeturl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">Hizmet Detayı</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"hizmetdetayurl\" value=\"";
    echo $Sonuc["hizmetdetayurl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">Haberler</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"haberurl\" value=\"";
    echo $Sonuc["haberurl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">Haber Detayı</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"haberdetayurl\" value=\"";
    echo $Sonuc["haberdetayurl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">Sayfa Detayı</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"sayfaurl\" value=\"";
    echo $Sonuc["sayfaurl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">İnsan Kaynakları</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"ikurl\" value=\"";
    echo $Sonuc["ikurl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">Sıkça Sorulan Sorular</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"sssurl\" value=\"";
    echo $Sonuc["sssurl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">Banka Hesapları</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"bankahesapurl\" value=\"";
    echo $Sonuc["bankahesapurl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">Hesap Oluştur</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"hesapolustururl\" value=\"";
    echo $Sonuc["hesapolustururl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">Giriş Yap</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"girisyapurl\" value=\"";
    echo $Sonuc["girisyapurl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t<div class=\"col-md-4\">\r\n\t\t\t\t\t\t\t<div class=\"card mb-4\">\r\n\t\t\t\t\t\t\t\t<div class=\"card-header\">Hesabım</div>\r\n\t\t\t\t\t\t\t\t<div class=\"card-body p-3\">\r\n\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-0\">\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\" name=\"hesabimurl\" value=\"";
    echo $Sonuc["hesabimurl"];
    echo "\" />\r\n\t\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<button type=\"submit\" name=\"sabit_url\" class=\"btn btn-success btn-icon-text btn-sm\">\r\n\t\t\t\t\t\t<i class=\"mdi mdi-spin mdi-loading\"></i>                                                    \r\n\t\t\t\t\t\tGÜNCELLE\r\n\t\t\t\t\t</button>\r\n\t\t\t\t</form>\t\t\t\t\t\t\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</div>\r\n\r\n</div>\r\n";
    mesaj("sabit_url", 1, "yes", "Başarı ile guncellenmiştir.");
    mesaj("sabit_url", 2, "no", "Hata oluştu tekrar deneyiniz.!");
    
} else {
    header("Location:" . $url . "/404" . $html . "");
    exit;
}

?>